import {fcmMembershipBlock,membershipDelta} from '../consumer/node_modules/ubukit-js/src/iteration-kernels.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {Worker} from 'node:worker_threads';
import {fcm,createSession,createWorkerClient,createRealtimeWorkerClient,runAsync,seededRandom,steps} from '../consumer/node_modules/ubukit-js/src/index.js';
import {stableDistance} from '../consumer/node_modules/ubukit-js/src/fcm-stable.js';
const input=rows=>({data:Float64Array.from(rows.flat()),nSamples:rows.length,nFeatures:rows[0].length});
function close(actual,expected,relative=5e-12,absolute=1e-320){expected=expected.flat?.(Infinity)??expected;assert.equal(actual.length,expected.length);for(let i=0;i<actual.length;++i)assert.ok(Math.abs(actual[i]-expected[i])<=absolute+relative*Math.max(Math.abs(expected[i]),Math.abs(actual[i])),`${i}: ${actual[i]} versus ${expected[i]}`)}
function finish(s){while(!s.status.done)s.step(1,{maxChunks:1,timeBudgetMs:0});return s.snapshot().result}
const ref=JSON.parse(fs.readFileSync(new URL('./highprecision-reference.json',import.meta.url)));
for(const c of ref.cases)test(`420-digit reference: ${c.name}`,()=>{const o={nClusters:c.centers.length,m:c.m,maxIterations:c.steps,tolerance:0,...c.initCenters?{initCenters:Float64Array.from(c.initCenters.flat())}:{initMembership:Float64Array.from(c.initMembership.flat())}};const r=fcm(input(c.x),o);close(r.centers,c.centers,c.name==='near-one-huge'?2e-13:8e-12);close(r.membership,c.membership,8e-12);assert.ok(r.centers.every(Number.isFinite));assert.ok(r.membership.every(Number.isFinite));});
const rng=seededRandom(318),n=31,d=128,k=5,data=Float64Array.from({length:n*d},()=>rng()*2-1),u=Float64Array.from({length:n*k},()=>rng()),opts={nClusters:k,initMembership:u,m:1000,maxIterations:3,tolerance:0,returnHistory:true,blockRows:7};
test('previously rejected D128 fixture and translated pair; exact segmented session parity',()=>{let first;for(const values of [data,Float64Array.from(data,(v,i)=>v-data[i%d])]){const x={data:values,nSamples:n,nFeatures:d},r=fcm(x,opts),s=createSession('fcm',x,opts);assert.deepEqual(finish(s),r);assert.equal(s.status.totalIterations,3);assert.ok(r.centers.every(Number.isFinite));for(let i=0;i<n;++i)assert.ok(Math.abs(r.membership.subarray(i*k,(i+1)*k).reduce((a,b)=>a+b,0)-1)<1e-14);if(!first)first=r;else{assert.deepEqual(r.membership,first.membership);for(let j=0;j<r.centers.length;++j)assert.ok(Math.abs((r.centers[j]+data[j%d])-first.centers[j])<1e-14)}s.dispose()}});
test('huge m session restarts preserve hidden finite-m weights',()=>{const x=input([[-1],[1]]),o={initCenters:Float64Array.of(-.5,.5),m:1e100,maxIterations:1,tolerance:0},s=createSession('fcm',x,o);finish(s);const exposed=s.snapshot().result;assert.deepEqual([...exposed.membership],[.5,.5,.5,.5]);exposed.membership.fill(0);s.updateParameters({maxIterations:1});const second=finish(s);close(second.centers,fcm(x,{...o,maxIterations:2}).centers,1e-14);s.configure(x,{...o,maxIterations:1});const third=finish(s);close(third.centers,fcm(x,{...o,maxIterations:3}).centers,1e-14);s.dispose()});
test('same-data m changes transform retained exact membership log weights',()=>{const x=input([[-1],[1]]),o={initCenters:Float64Array.of(-.5,.5),m:1e100,maxIterations:1,tolerance:0},s=createSession('fcm',x,o);finish(s);s.updateParameters({m:1e100*2});const r=finish(s);const a=.8,p=2*((1+a)/(1-a))**2; // ratio of distance-based weights gets the m_new/m_old exponent
const ratio=((1+a)/(1-a))**4;close(r.centers,[(1-ratio)/(1+ratio),(ratio-1)/(ratio+1)],1e-13);s.dispose()});
test('nonzero tiny and overflowing distances stay distinct from exact zeros',()=>{assert.equal(stableDistance(Float64Array.of(0),0,Float64Array.of(Number.MIN_VALUE),0,1).log,2*Math.log(Number.MIN_VALUE));assert.equal(stableDistance(Float64Array.of(0),0,Float64Array.of(0),0,1).log,-Infinity);assert.ok(Number.isFinite(stableDistance(Float64Array.of(-1e308),0,Float64Array.of(1e308),0,1).log));});
test('default membership convergence warns through center-motion diagnostic',()=>{const r=fcm(input([[-1],[1]]),{initCenters:Float64Array.of(-.5,.5),m:1e100});assert.equal(r.converged,true);assert.equal(r.iterations,1);assert.equal(r.membershipConvergenceOnly,true);assert.ok(r.centerRelativeDelta>.1);assert.equal(r.objectiveRepresentation,'underflow');assert.ok(Number.isFinite(r.objectiveLog))});
test('unrepresentable objective is explicit, never clipped or mislabeled finite',()=>{const r=fcm(input([[-1e308],[1e308]]),{initMembership:Float64Array.of(1,1),nClusters:1,m:2,maxIterations:1,tolerance:0});assert.equal(r.objective,Infinity);assert.equal(r.objectiveRepresentation,'overflow');assert.ok(Number.isFinite(r.objectiveLog));assert.ok(r.centers.every(Number.isFinite));});
test('unguarded ordinary kernel range failure falls back without duplicate commits',()=>{const x=input([[0],[1e-139]]),o={initMembership:Float64Array.of(1,1e-10,1,1e-100),m:2,maxIterations:3,tolerance:0};const r=fcm(x,o),s=createSession('fcm',x,o);assert.equal(r.numericalMode,'log-domain');assert.deepEqual(finish(s),r);assert.equal(s.status.totalIterations,3);s.dispose();});
test('stable cancellation and runAsync exact output',async()=>{const x=input([[-1],[1]]),o={initCenters:Float64Array.of(-.5,.5),m:1e100,maxIterations:3,tolerance:0,blockRows:1};assert.deepEqual(await runAsync('fcm',x,{...o,timeBudgetMs:0}),fcm(x,o));let count=0;assert.throws(()=>fcm(x,{...o,shouldCancel:()=>++count>5}),{name:'AbortError'});});
test('real Node one-shot and realtime Workers preserve stable output and same-data restarts',async()=>{const x=input([[-1],[1]]),o={initCenters:Float64Array.of(-.5,.5),m:1e100,maxIterations:1,tolerance:0};const one=createWorkerClient({workerFactory:()=>new Worker(new URL('../consumer/node_modules/ubukit-js/src/worker.js',import.meta.url),{type:'module'})});const realtime=createRealtimeWorkerClient({workerFactory:()=>new Worker(new URL('../consumer/node_modules/ubukit-js/src/realtime-worker.js',import.meta.url),{type:'module'})});try{assert.deepEqual(await one.run('fcm',x,o),fcm(x,o));assert.deepEqual((await realtime.run('fcm',x,o,{warmStart:false})).result,fcm(x,o));const second=(await realtime.run('fcm',x,o)).result;close(second.centers,fcm(x,{...o,maxIterations:2}).centers,1e-14)}finally{one.dispose();realtime.dispose()}});

test('initial normalization never erases an otherwise usable tiny column',()=>{const r=fcm(input([[0],[10]]),{nClusters:2,initMembership:Float64Array.of(1e308,1e-100,1e308,2e-100),m:2,maxIterations:1,tolerance:0});close(r.centers,[5,8],2e-13);});
test('positive objective whose logarithm overflows is still underflow, never exact zero',()=>{const r=fcm(input([[0],[2]]),{nClusters:5,initMembership:new Float64Array(10).fill(1),m:Number.MAX_VALUE,maxIterations:1,tolerance:0});assert.equal(r.objective,0);assert.equal(r.objectiveRepresentation,'underflow');assert.equal(r.objectiveLog,-Infinity);});

test('high-m initial normalization retains sub-ulp row normalizers',()=>{for(const m of [1e20,1e100,1e308]){const r=fcm(input([[0],[10]]),{initMembership:Float64Array.of(1,1,1,1-Number.EPSILON/2),m,maxIterations:1,tolerance:0});assert.deepEqual([...r.centers],[10,0]);}});
test('opposite huge terms retain representable cancellation residuals',()=>{const big=1e308;const b=new DataView(new ArrayBuffer(8));b.setFloat64(0,big);b.setBigUint64(0,b.getBigUint64(0)-1n);const lower=b.getFloat64(0);for(const [values,expected]of[[[big,big,-lower,-lower,0],(big-lower)*2/5],[[8e307,1,-8e307],1/3],[[-big,big,1e-320],1e-320/3]]){const r=fcm(input(values.map(v=>[v])),{initMembership:new Float64Array(values.length).fill(1),nClusters:1,m:2,maxIterations:1,tolerance:0});assert.equal(r.centers[0],expected);}});
test('translation cannot erase original tiny coordinates',()=>{const r=fcm(input([[1],[0],[1e-200]]),{initMembership:Float64Array.of(0,1,1,0,1,0),m:2,maxIterations:1,tolerance:0});close(r.centers,[5e-201,1],1e-14);});

test('subnormal weighted numerator is rounded only after division',()=>{const r=fcm(input([[0],[Number.MIN_VALUE],[Number.MIN_VALUE],[Number.MIN_VALUE]]),{initMembership:Float64Array.of(1,0,.7,.3,.7,.3,.7,.3),m:2,maxIterations:1,tolerance:0});assert.deepEqual([...r.centers],[Number.MIN_VALUE,Number.MIN_VALUE]);});
test('huge m preserves adjacent tiny initial numerator ratios',()=>{const tiny=1e-100,b=new DataView(new ArrayBuffer(8));b.setFloat64(0,tiny);b.setBigUint64(0,b.getBigUint64(0)+1n);const next=b.getFloat64(0);for(const m of[1e20,1e100,1e308]){const r=fcm(input([[0],[10]]),{initMembership:Float64Array.of(1,tiny,1,next),m,maxIterations:1,tolerance:0});assert.equal(r.centers[1],10);if(m===1e308)assert.equal(r.centers[0],0);}});

test('huge-m raw row ratios compare exact cross-products across changing maxima',()=>{
  const nextUp=v=>{const b=new DataView(new ArrayBuffer(8));b.setFloat64(0,v);b.setBigUint64(0,b.getBigUint64(0)+1n);return b.getFloat64(0)};
  for(const scale of [2**-900,1,2**900])for(const m of [1e20,1e100,1e308]){
    const r=fcm(input([[0],[10]]),{initMembership:Float64Array.of(scale,3*scale,nextUp(1)*scale,nextUp(nextUp(3))*scale),m,maxIterations:1,tolerance:0});
    assert.deepEqual([...r.centers],[0,10]);
  }
});
test('64 independent Fraction-oracle initial membership row comparisons',()=>{const cases=JSON.parse(fs.readFileSync(new URL('./initial-ratio-fraction-oracle.json',import.meta.url)));assert.equal(cases.length,64);for(const c of cases){const r=fcm(input([[0],[10]]),{nClusters:2,initMembership:Float64Array.from(c.raw),m:1e20,maxIterations:1,tolerance:0});close(r.centers,c.expected,1e-13,1e-13);}});

test('ordinary delta underflow cannot report false convergence in sync, generator, or session',()=>{const x=input([[0],[2e-100],[1]]),o={initMembership:Float64Array.of(1,0,1,0,0,1),m:2,maxIterations:1,tolerance:1e-210,blockRows:1},r=fcm(x,o);assert.equal(r.numericalMode,undefined);close([r.delta],[Math.SQRT2*1e-200],2e-15,0);assert.equal(r.converged,false);let generated;for(const it=steps('fcm',x,o);;){const next=it.next();if(next.done){generated=next.value;break;}}assert.deepEqual(generated,r);const s=createSession('fcm',x,o);assert.deepEqual(finish(s),r);s.dispose();});
test('stable delta underflow is recovered before convergence',()=>{const x=input([[0],[2e-100],[1]]),initial=Float64Array.of(1,0,1e-170,1,0,1e-170,0,1,1e-170),o={initMembership:initial,m:2,maxIterations:1,tolerance:1e-180,blockRows:1},r=fcm(x,o);assert.equal(r.numericalMode,'log-domain');const differences=Float64Array.from(r.membership,(v,i)=>v-initial[i]);close([r.delta],[Math.hypot(...differences)],2e-15,0);assert.ok(r.delta>o.tolerance);assert.equal(r.converged,false);const s=createSession('fcm',x,o);assert.deepEqual(finish(s),r);s.dispose();});

test('cached-power membership kernel retains tiny stopping differences before overwriting old U',()=>{const old=Float64Array.of(1,0),next=new Float64Array(2),accum={delta2:0,objective:0};fcmMembershipBlock(Float64Array.of(0),Float64Array.of(1e-100,1e100),old,next,new Float64Array(2),0,1,1,2,3,accum,null,true);assert.equal(accum.delta2,0);close([membershipDelta(accum)],[1e-200],1e-13,0);assert.equal(old[1],0);});
