import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { Worker } from 'node:worker_threads';
import { run, runAsync, steps, som, somBatch, som_batch, createSession, createWorkerClient, createRealtimeWorkerClient, algorithms, sessionAlgorithms } from '../consumer/node_modules/ubukit-js/src/index.js';
const fixture=JSON.parse(fs.readFileSync(new URL('../fixtures/som-shared-reference.json',import.meta.url)));
const input=rows=>({data:Float64Array.from(rows.flat()),nSamples:rows.length,nFeatures:rows[0].length});
const close=(a,b,tol=2e-12)=>{assert.equal(a.length,b.length);for(let i=0;i<a.length;i++)assert.ok(Math.abs(a[i]-b[i])<=tol*Math.max(1,Math.abs(b[i])),`${i}: ${a[i]} vs ${b[i]}`);};
const finish=s=>{for(let i=0;!s.status.done;i++){assert.ok(i<100000);s.step(1,{timeBudgetMs:1e6,maxChunks:1});}return s.snapshot().result;};
const options=c=>({...c.options,gridShape:c.options.gridShape.slice(),initialPrototypes:Float64Array.from(c.initialPrototypes.flat()),blockRows:2,blockUnits:1});
for(const c of fixture.cases)test(`independent scalar trajectory: ${c.name}`,()=>{
 const x=input(c.data),o=options(c),s=createSession(c.algorithm,x,o);let previous=0;
 while(!s.status.done){s.step(1,{timeBudgetMs:1e6,maxChunks:1});if(s.status.iteration>previous){close(s.snapshot().result.centers,c.expected.history[s.status.iteration-1].flat());previous=s.status.iteration;}}
 const actual=s.snapshot().result;close(actual.centers,c.expected.centers.flat());assert.deepEqual([...actual.labels],c.expected.labels);
 assert.equal(actual.unit,c.algorithm==='som'?'sample':'epoch');assert.equal(actual.iterations,c.options.maxIterations);assert.equal(actual.converged,false);
 assert.deepEqual(actual,run(c.algorithm,x,o));
});
for(const algorithm of ['som','som_batch']){
 test(`${algorithm}: zero epochs, default 16x16 and finite arbitrary dimension`,()=>{for(const d of[1,3,17,257]){const r=run(algorithm,input([Array(d).fill(0)]),{epochs:0});assert.equal(r.nUnits,256);assert.equal(r.centers.length,256*d);assert.ok(r.centers.every(v=>v===0));assert.equal(r.iterations,0);assert.deepEqual([...r.labels],[0]);assert.deepEqual(r.gridShape,[16,16]);}});
 test(`${algorithm}: rectangular lattice, empty unit retention and exact zeros`,()=>{const x=input([[0,0],[0,0],[10,0]]),w=Float64Array.of(0,0,5,0,10,0,30,30,40,40,50,50);const r=run(algorithm,x,{gridShape:[3,2],initialPrototypes:w,maxIterations:1,sigma:0,...algorithm==='som'?{learningRate:0}:{}});assert.deepEqual([...r.centers.slice(6)],[30,30,40,40,50,50]);assert.deepEqual([...r.labels],[0,0,2]);assert.deepEqual([...r.embedding],[0,0,0,0,2,0]);});
 test(`${algorithm}: inputs, prototypes, option grids and snapshots are owned`,()=>{const c=fixture.cases.find(v=>v.algorithm===algorithm),x=input(c.data),o=options(c),expected=run(algorithm,x,o),s=createSession(algorithm,x,o);x.data.fill(999);o.initialPrototypes.fill(999);o.gridShape[0]=99;const r=finish(s);close(r.centers,expected.centers);r.centers.fill(-5);r.gridShape[0]=99;assert.notEqual(s.snapshot().result.centers[0],-5);assert.equal(s.snapshot().result.gridShape[0],2);});
 test(`${algorithm}: invalid revisions preserve a complete checkpoint`,()=>{const c=fixture.cases.find(v=>v.algorithm===algorithm),s=createSession(algorithm,input(c.data),options(c));s.step(1,{timeBudgetMs:1e6});const before=s.snapshot();for(const patch of[{sigma:NaN},{sigma:-1},{sigma:.1,sigmaEnd:.5},{schedule:'bad'},{gridShape:[0,2]},{initialPrototypes:Float64Array.of(Infinity)},{maxIterations:-1},{maxMemoryBytes:1},{blockUnits:0},{epochs:1.1},{shuffle:true},{kernelBackend:'wasm'},{initialMemberships:Float64Array.of(1)}]){assert.throws(()=>s.updateParameters(patch));assert.deepEqual(s.snapshot(),before);}});
 test(`${algorithm}: reset, parameter warm start, data resize, shape change and disposal`,()=>{const c=fixture.cases.find(v=>v.algorithm===algorithm),x=input(c.data),o=options(c),s=createSession(algorithm,x,o),first=finish(s);s.reset();assert.deepEqual(finish(s),first);s.updateParameters({sigma:.8,sigmaEnd:.1});assert.equal(s.status.invalidation.kind,'centers');finish(s);s.updateData(input(c.data.slice(1)));assert.equal(s.status.invalidation.kind,'centers');assert.equal(finish(s).labels.length,c.data.length-1);s.configure(x,{...o,gridShape:[1,4],initialPrototypes:undefined,initializer:'sample'});assert.equal(s.status.invalidation.kind,'cold');assert.deepEqual(finish(s).gridShape,[1,4]);s.dispose();assert.throws(()=>s.step(),/disposed/);});
 test(`${algorithm}: partial work stays private and zero soft budget advances one chunk`,()=>{const c=fixture.cases.find(v=>v.algorithm===algorithm),s=createSession(algorithm,input(c.data),options(c));const a=s.step(10,{timeBudgetMs:0});assert.equal(a.chunks,1);assert.equal(a.completedIterations,0);assert.equal(s.snapshot().result,null);while(s.status.iteration===0)s.step(1,{timeBudgetMs:0});const previous=s.snapshot().result;s.step(10,{timeBudgetMs:0});assert.deepEqual(s.snapshot().result,previous);});
 test(`${algorithm}: cancellation keeps the last committed model, restart succeeds`,()=>{const c=fixture.cases.find(v=>v.algorithm===algorithm),controller=new AbortController(),s=createSession(algorithm,input(c.data),{...options(c),signal:controller.signal});while(!s.status.iteration)s.step(1,{timeBudgetMs:0});const last=s.snapshot().result;s.step(1,{timeBudgetMs:0});controller.abort();assert.throws(()=>s.step(),{name:'AbortError'});assert.deepEqual(s.snapshot().result,last);s.updateParameters({signal:undefined});assert.ok(finish(s).centers.every(Number.isFinite));});
 test(`${algorithm}: PCA works for one-row, rank-deficient and full-dimensional input`,()=>{for(const rows of[[[4,4,4]],[[0,0,0],[1,1,1],[2,2,2]],[[0,0,1],[1,0,2],[0,2,4],[3,1,-1]]]){const x=input(rows),o={gridShape:[2,2],initializer:'pca',maxIterations:0};const a=run(algorithm,x,o),b=run(algorithm,x,o);assert.ok(a.centers.every(Number.isFinite));assert.deepEqual(a,b);assert.equal(a.initialization.kind,'pca-jacobi');}});
 test(`${algorithm}: seeded sample initialization reproducible and shared RNG exact`,()=>{const x=input([[0],[1],[2],[3],[4],[5]]),o={gridShape:[3,2],epochs:0,seed:42};assert.deepEqual([...run(algorithm,x,o).centers],[3,2,5,4,1,3]);assert.deepEqual(run(algorithm,x,o),run(algorithm,x,o));});
 test(`${algorithm}: async and direct iteration identical`,async()=>{const c=fixture.cases.find(v=>v.algorithm===algorithm),x=input(c.data),o=options(c),r=run(algorithm,x,o);assert.deepEqual(await runAsync(algorithm,x,{...o,timeBudgetMs:0}),r);let it=steps(algorithm,x,o),v;do{v=it.next();}while(!v.done);assert.deepEqual(v.value,r);});
 test(`${algorithm}: module Worker and realtime Worker use additive registry`,async()=>{const c=fixture.cases.find(v=>v.algorithm===algorithm),x=input(c.data),o=options(c),expected=run(algorithm,x,o);const a=createWorkerClient({workerFactory:()=>new Worker(new URL('../consumer/node_modules/ubukit-js/src/worker.js',import.meta.url),{type:'module'})}),b=createRealtimeWorkerClient({workerFactory:()=>new Worker(new URL('../consumer/node_modules/ubukit-js/src/realtime-worker.js',import.meta.url),{type:'module'})});try{assert.deepEqual(await a.run(algorithm,x,o),expected);const result=await b.run(algorithm,x,o,{timeBudgetMs:0,maxChunks:1});assert.deepEqual(result.result,expected);}finally{a.dispose();b.dispose();}});
}
test('direct exports and canonical registry names are additive',()=>{assert.equal(somBatch,som_batch);assert.ok(algorithms.includes('som')&&algorithms.includes('som_batch'));assert.ok(sessionAlgorithms.includes('som')&&sessionAlgorithms.includes('som_batch'));const c=fixture.cases[0],x=input(c.data);assert.deepEqual(som(x,options(c)),run('som',x,options(c)));});
test('online step is one sample, batch step is one frozen-assignment epoch',()=>{const x=input([[0],[10]]),o={gridShape:[1,1],initialPrototypes:Float64Array.of(0),maxIterations:1,sigma:0};assert.equal(som(x,{...o,learningRate:1}).centers[0],0);assert.equal(somBatch(x,o).centers[0],5);assert.equal(som(x,{...o,epochs:2,maxIterations:undefined}).iterations,4);assert.equal(somBatch(x,{...o,epochs:2,maxIterations:undefined}).iterations,2);assert.throws(()=>somBatch(x,{...o,learningRate:1}),/weighted means/);});
test('constant tiny and huge finite data remain fixed without accumulator underflow',()=>{for(const v of[1e-320,1e308]){const x=input([[v],[v],[v]]),o={gridShape:[2,2],epochs:2,sigma:0};for(const a of['som','som_batch'])assert.ok(run(a,x,o).centers.every(z=>z===v));}});
test('unrepresentable distances fail explicitly instead of creating false ties',()=>{for(const a of['som','som_batch'])for(const v of[1e-200,1e200])assert.throws(()=>run(a,input([[0],[v]]),{gridShape:[1,1],initialPrototypes:Float64Array.of(0),epochs:1}),/distance/);});
test('no sample-unit matrix in memory bound',()=>{const n=10000,d=3,x={data:new Float64Array(n*d),nSamples:n,nFeatures:d};const r=somBatch(x,{epochs:0,maxMemoryBytes:2e6});assert.ok(r.stats.estimatedPrimaryBytes<2e6);assert.equal(r.membership,undefined);});
test('batch isolated singleton groups retain low values beside large offsets',()=>{const r=somBatch(input([[1e16],[1]]),{gridShape:[2,1],initialPrototypes:Float64Array.of(1e16,1),sigma:0,epochs:1});assert.deepEqual([...r.centers],[1e16,1]);});
test('tiny nonempty Gaussian mass retains its weighted mean',()=>{const r=somBatch(input([[0],[1e-100]]),{gridShape:[3,1],initialPrototypes:Float64Array.of(0,1e-100,1),sigma:Math.sqrt(1/(2*690)),epochs:1});assert.ok(Math.abs(r.centers[2]/1e-100-1)<1e-14);});
test('on-demand current-model projection is fresh and does not mutate committed state',()=>{const c=fixture.cases[0],s=createSession('som',input(c.data),options(c));while(!s.status.iteration)s.step(1,{timeBudgetMs:0});const before=s.snapshot().result;assert.equal(before.labels,null);const projected=s.snapshot({project:true}).result;assert.equal(projected.projectionStatus,'current-prototypes');const expected=som(input(c.data),{gridShape:before.gridShape,initialPrototypes:before.centers,maxIterations:0});assert.deepEqual(projected.labels,expected.labels);assert.deepEqual(projected.embedding,expected.embedding);assert.deepEqual(s.snapshot().result,before);});
test('batch cold repair preserves raw cancellation residuals lost by rounded group means',()=>{for(const a of[1e16,1e100]){const r=somBatch(input([[a],[1],[-a]]),{gridShape:[1,1],initialPrototypes:Float64Array.of(0),sigma:0,epochs:1});assert.equal(r.centers[0],1/3);assert.equal(r.stats.stableBatchRepair,true);}});
test('batch signed cancellation repair covers similar-magnitude operands',()=>{for(const [rows,expected] of[[[1e16,1e16+2,-1e16,-1e16],.5],[[1e10,1e10+1e-5,-1e10,-1e10],2.384185791015625e-6]]){const r=somBatch(input(rows.map(x=>[x])),{gridShape:[1,1],initialPrototypes:Float64Array.of(0),sigma:0,epochs:1});assert.equal(r.centers[0],expected);assert.equal(r.stats.stableBatchRepair,true);}});
test('online convex blend preserves ill-conditioned endpoint and cancellation contributions',()=>{const o={gridShape:[1,1],initialPrototypes:Float64Array.of(1e16),sigma:0,epochs:1};assert.equal(som(input([[-1e16+2]]),{...o,learningRate:.5}).centers[0],1);assert.equal(som(input([[1]]),{...o,learningRate:1-2**-53}).centers[0],2.1102230246251565);});
