import test from 'node:test';
import assert from 'node:assert/strict';
import { Worker } from 'node:worker_threads';
import { createWorkerClient, run } from '../src/index.js';
const factory=()=>new Worker(new URL('../src/worker.js',import.meta.url),{type:'module'});
const input=()=>({data:Float64Array.of(0,0,1,1,9,9,10,10),nSamples:4,nFeatures:2});
test('Worker results, progress, buffers and error recovery',async()=>{const client=createWorkerClient({workerFactory:factory});try{let progress=0;const x=input();const actual=await client.run('fcm',x,{nClusters:2,seed:7,onProgress:()=>progress++});assert.deepEqual(actual,run('fcm',x,{nClusters:2,seed:7}));assert.ok(progress>0);assert.ok(x.data.byteLength>0);const transferred=input();await client.run('kmeans',transferred,{nClusters:2,transferInput:true});assert.equal(transferred.data.byteLength,0);await assert.rejects(client.run('bad',input()),/Unknown algorithm/);const r=await client.run('kmeans',input(),{nClusters:2});assert.equal(r.labels.length,4);}finally{client.dispose();}});
test('Worker cancellation is prompt and client reusable',async()=>{const client=createWorkerClient({workerFactory:factory});try{const controller=new AbortController();const n=2000,d=5;const x={data:new Float64Array(n*d),nSamples:n,nFeatures:d};const start=performance.now();let progressSeen=false, ticks=0,abortStarted=0;const timer=setInterval(()=>ticks++,5);const job=client.run('fcm',x,{nClusters:12,maxIterations:100000,tolerance:0,signal:controller.signal,onProgress:()=>{if(!progressSeen){progressSeen=true;setTimeout(()=>{abortStarted=performance.now();controller.abort();},15);}}});try{await assert.rejects(job,{name:'AbortError'});}finally{clearInterval(timer);}assert.ok(progressSeen);assert.ok(ticks>0);assert.ok(performance.now()-abortStarted<1000);assert.ok(performance.now()-start<2000);const result=await client.run('kmeans',input(),{nClusters:2});assert.equal(result.labels.length,4);}finally{client.dispose();}});
test('busy, pre-aborted, and disposed states',async()=>{const client=createWorkerClient({workerFactory:factory});await assert.rejects(client.run('kmeans',input(),{nClusters:2,signal:AbortSignal.abort()}),{name:'AbortError'});const pending=client.run('kmeans',input(),{nClusters:2});await assert.rejects(client.run('kmeans',input(),{nClusters:2}),/busy/);await pending;client.dispose();await assert.rejects(client.run('kmeans',input()),/disposed/);});
