/** Byte-exact rebuild/check. Only local generated bytes and JSON verification records are written. */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { root, runtime, inventory, hash, capturedBytes, loadWabt, verifyPreservedSources, readJSON } from './common.mjs';
verifyPreservedSources();
const wabt=await loadWabt();
fs.mkdirSync(path.join(root,'verification'),{recursive:true});
const dir=path.join(root,'.generated/rebuilt');fs.mkdirSync(dir,{recursive:true});
function sections(b){let p=8;const out=[];const uleb=()=>{let n=0,s=0,v;do{assert.ok(p<b.length);v=b[p++];n|=(v&127)<<s;s+=7;}while(v&128);return n>>>0;};
 while(p<b.length){const start=p,id=b[p++],size=uleb(),payload=p,end=p+size;assert.ok(end<=b.length);let name=null;if(id===0){const len=uleb();name=b.subarray(p,p+len).toString();}out.push({id,name,offset:start,payloadBytes:size,encodedBytes:end-start,sha256:hash(b.subarray(start,end)),raw:b.subarray(start,end)});p=end;}return out;}
function core(b){return Buffer.concat([b.subarray(0,8),...sections(b).filter(s=>s.id!==0).map(s=>s.raw)]);}
function build(file,debug){const m=wabt.parseWat(file,fs.readFileSync(path.join(root,file),'utf8'),{simd:true});try{m.resolveNames();m.validate({simd:true});return Buffer.from(m.toBinary({write_debug_names:debug}).buffer);}finally{m.destroy();}}
const originals=[];const originalBuilds=[];
for(const src of inventory.original_wat){
 assert.equal(hash(fs.readFileSync(path.join(root,src.path))),src.sha256,'Original WAT changed');
 if(!/^\s*\(module\b/.test(fs.readFileSync(path.join(root,src.path),'utf8'))){originals.push({...src,status:'fragment_not_standalone',note:'Historical code-generation fragment, not a self-contained module; included in a full recovered module by the historical generator.'});continue;}
 const modes=src.path.includes('/rmcm/')?[true]:[false];
 for(const debug of modes){const bytes=build(src.path,debug),sha256=hash(bytes),matches=inventory.binaries.filter(b=>b.sha256===sha256).map(b=>b.sha256);assert.ok(WebAssembly.validate(bytes));
 originalBuilds.push({source:src.path,bytes,sha256,write_debug_names:debug});
 originals.push({source:src.path,source_sha256:src.sha256,bytes:bytes.length,sha256,write_debug_names:debug,webassembly_valid:true,matching_embedded_sha256:matches});}
}
const binaries=[];
for(const b of inventory.binaries){
 const expected=capturedBytes(b);assert.equal(hash(expected),b.sha256,'Captured binary changed');assert.ok(WebAssembly.validate(expected));
 const m=new WebAssembly.Module(expected), ss=sections(expected);
 const file='reconstructed-wat/'+b.sha256+'.reconstructed.wat';
 const trials=[false,true].map(debug=>{const bytes=build(file,debug);return{bytes,sha256:hash(bytes),write_debug_names:debug,byte_identical:bytes.equals(expected),standard_sections_identical:core(bytes).equals(core(expected)),custom_sections:sections(bytes).filter(s=>s.id===0).map(({raw,...s})=>s)};});
 const best=trials.find(t=>t.byte_identical)??trials.find(t=>t.standard_sections_identical);assert.ok(best,'Executable sections changed: '+b.sha256);assert.ok(best.byte_identical,'Byte-exact round-trip required: '+b.sha256);
 const output='.generated/rebuilt/'+b.sha256+'.wasm';fs.writeFileSync(path.join(root,output),best.bytes);
 const original=originalBuilds.find(o=>o.sha256===b.sha256);
 binaries.push({sha256:b.sha256,bytes:b.bytes,exports:WebAssembly.Module.exports(m),imports:WebAssembly.Module.imports(m),original_source:original?.source??null,original_source_match:!!original,reconstructed_source:file,reconstructed_source_sha256:hash(fs.readFileSync(path.join(root,file))),roundtrip:{path:output,write_debug_names:best.write_debug_names,sha256:best.sha256,bytes:best.bytes.length,byte_identical:best.byte_identical,standard_sections_identical:best.standard_sections_identical,custom_sections:best.custom_sections},original_custom_sections:ss.filter(s=>s.id===0).map(({raw,...s})=>s),trials:trials.map(({bytes,...t})=>({...t,bytes:bytes.length}))});
}
// Confirm wrappers are exact captured files, and still contain their captured binary.
const current=inventory.current.map(c=>{const wrapper=fs.readFileSync(path.join(runtime,'src',c.wrapper));assert.equal(hash(wrapper),c.wrapper_sha256);const match=wrapper.toString().match(/const bytes\s*=\s*new Uint8Array\((\[[\s\S]*?\])\);/);assert.ok(match);assert.equal(hash(Buffer.from(JSON.parse(match[1]))),c.sha256);return{...c,...binaries.find(b=>b.sha256===c.sha256)};});
const report={schema_version:1,observed_utc:new Date().toISOString(),node:process.version,platform:process.platform,arch:process.arch,wabt_version:'1.0.39',no_runtime_modification:true,no_optimization_pass:true,runtime_package_version:readJSON(path.join(runtime,'package.json')).version,generated_outputs_ephemeral:true,summary:{unique_binaries:binaries.length,current_binaries:current.length,original_wat_files:inventory.original_wat.length,original_standalone_modules_compiled:originals.filter(x=>x.webassembly_valid).length,current_original_byte_identical:current.filter(x=>x.original_source_match).length,current_reconstructed_byte_identical:current.filter(x=>x.roundtrip.byte_identical).length,all_reconstructed_byte_identical:binaries.filter(x=>x.roundtrip.byte_identical).length,all_reconstructed_standard_sections_identical:binaries.filter(x=>x.roundtrip.standard_sections_identical).length},current,binaries,originals};
fs.writeFileSync(path.join(root,'verification/rebuild.json'),JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify(report.summary,null,2));
