/** Bounded deterministic correctness checks, deliberately no speed/benchmark claims. */
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import{pathToFileURL}from'node:url';
import { root, runtime, inventory, hash, capturedBytes } from './common.mjs';
const build=JSON.parse(fs.readFileSync(path.join(root,'verification/rebuild.json')));
// A disposable copied runtime executes rebuilt bytes. No verified source or package is edited.
const rebuilt=path.join(root,'.generated/rebuilt-runtime');fs.mkdirSync(rebuilt,{recursive:true});fs.cpSync(path.join(runtime,'src'),path.join(rebuilt,'src'),{recursive:true});fs.copyFileSync(path.join(runtime,'package.json'),path.join(rebuilt,'package.json'));
for(const c of build.current){const file=path.join(rebuilt,'src',c.wrapper),old=fs.readFileSync(file,'utf8'),bytes=fs.readFileSync(path.join(root,c.roundtrip.path));assert.equal(hash(bytes),c.sha256);fs.writeFileSync(file,old.replace(/const bytes\s*=\s*new Uint8Array\((\[[\s\S]*?\])\);/,'const bytes=new Uint8Array('+JSON.stringify([...bytes])+');'));}
for(const c of inventory.current)assert.equal(hash(fs.readFileSync(path.join(runtime,'src',c.wrapper))),c.wrapper_sha256);
const api=Object.assign({},...await Promise.all(['clustering.js','som-olp.js','neighborhood.js','rmcm.js'].map(f=>import(pathToFileURL(path.join(rebuilt,'src',f)))))),km=await import(pathToFileURL(path.join(rebuilt,'src/kmeans-wasm.js'))),somw=await import(pathToFileURL(path.join(rebuilt,'src/som-training-wasm.js'))),pcaw=await import(pathToFileURL(path.join(rebuilt,'src/som-pca-wasm.js'))),metric=await import(pathToFileURL(path.join(rebuilt,'src/metric-wasm.js'))),rmw=await import(pathToFileURL(path.join(rebuilt,'src/rmcm-wasm.js'))),oldRm=await import(pathToFileURL(path.join(runtime,'src/rmcm-wasm.js')));
let seed=211859;const rnd=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/2**32;},matrix=(n,d,scale=1)=>({data:Float64Array.from({length:n*d},()=>scale*(rnd()*2-1)),nSamples:n,nFeatures:d});
const clean=r=>{const{kernel,...rest}=r;return rest;};
const outcome=f=>{try{return{value:clean(f())};}catch(e){return{error:e.name,message:e.message};}};
const walk=it=>{const events=[];let r;while(!(r=it.next()).done)events.push(r.value);return{events,value:clean(r.value)};};
const groups=[];let current=null;const eq=(a,b,label)=>{assert.deepEqual(a,b,label);current.checks++;};const ok=(a,label)=>{assert.ok(a,label);current.checks++;};
async function group(name,f){current={name,checks:0,status:'running'};groups.push(current);try{await f();current.status='passed';}catch(e){current.status='failed';current.error=e.stack;throw e;}}
function dist(x,i,j){let s=0;for(let f=0;f<x.nFeatures;f++){const d=x.data[i*x.nFeatures+f]-x.data[j*x.nFeatures+f];s+=d*d;}return Math.sqrt(s);}
let failure;
try{
await group('All 7 captured/rebuilt module ABIs and initial memory',()=>{for(const b of build.binaries){const a=new WebAssembly.Module(capturedBytes(inventory.binaries.find(c=>c.sha256===b.sha256))),z=new WebAssembly.Module(fs.readFileSync(path.join(root,b.roundtrip.path)));eq(WebAssembly.Module.exports(z),WebAssembly.Module.exports(a));eq(WebAssembly.Module.imports(z),WebAssembly.Module.imports(a));eq(new WebAssembly.Instance(z).exports.memory.buffer.byteLength,65536);}});
await group('K-means current scalar/rebuilt SIMD parity',()=>{
 for(let t=0;t<56;t++){const d=[1,2,3,8,17,32,64][t%7],n=13+t%15,k=1+t%17,x=matrix(n,d),centers=matrix(k,d).data;if(t%11===0)x.data.fill(0);if(t%13===0)centers.fill(0);const o={initCenters:centers,nClusters:k,maxIterations:3,blockRows:1+t%9};const a=api.kmeans(x,{...o,kernelBackend:'wasm'}),b=api.kmeans(x,{...o,kernelBackend:'javascript'});eq(clean(a),clean(b));ok(a.kernel.wasmAssignmentRows>0);}
 const x=matrix(35,17),o={nClusters:9,seed:31,maxIterations:3,blockRows:7};eq(walk(api.kmeansSteps(x,{...o,kernelBackend:'wasm'})),walk(api.kmeansSteps(x,{...o,kernelBackend:'javascript'})));
});
await group('K-means zero, underflow, overflow and fallback outcome parity',()=>{for(const scale of[0,1e-200,1e-160,1e150,1e154])for(const d of[1,3,8,17]){const x=matrix(7,d,scale),o={nClusters:3,initCenters:matrix(3,d,scale).data,maxIterations:2,blockRows:3};eq(outcome(()=>api.kmeans(x,{...o,kernelBackend:'wasm'})),outcome(()=>api.kmeans(x,{...o,kernelBackend:'javascript'})));}});
await group('SOM training, PCA and events against current scalar paths',()=>{
 for(let t=0;t<28;t++){const d=[1,2,3,8,17,32,64][t%7],x=matrix(13+t%9,d),grid=matrix(1+t%13,1+t%3),o={grid,initializer:'sample',seed:11,gamma:t%3===0?0:.37,lambda:1.7,maxIterations:3,tolerance:0,blockRows:1+t%9};const a=api.somOlp(x,{...o,kernelBackend:'wasm'}),b=api.somOlp(x,{...o,kernelBackend:'javascript'});eq(clean(a),clean(b));eq(a.kernel.training,'wasm');}
 for(const[n,d]of[[35,32],[41,33],[50,64]]){const x=matrix(n,d),o={grid:matrix(9,2),maxIterations:2,tolerance:0,blockRows:7,gamma:.3,lambda:2};const a=api.somOlp(x,{...o,kernelBackend:'wasm'}),b=api.somOlp(x,{...o,kernelBackend:'javascript'});eq(clean(a),clean(b));eq(a.kernel.pca,'wasm');eq(walk(api.somOlpSteps(x,{...o,kernelBackend:'wasm'})),walk(api.somOlpSteps(x,{...o,kernelBackend:'javascript'})));}
});
await group('Metric reconstructed row/rank/histogram and end-to-end scalar parity',()=>{
 for(const n of[11,17,33])for(const d of[1,2,3,8,17,32]){const x=matrix(n,d),y=matrix(n,2);if(d===1){x.data.fill(0);y.data.fill(0);}for(const rankMethod of['auto','histogram','radix']){const o={embedding:y,k:Math.min(5,Math.floor((n-1)/2)),rankMethod,blockRows:3},a=api.neighborhood(x,{...o,distanceBackend:'wasm'}),b=api.neighborhood(x,{...o,distanceBackend:'javascript'});eq(a.qualities,b.qualities);eq(a.stats.wasmDistances,true);}
 const w=metric.wasmRows(x,y,1e7,n-1);ok(w);for(const i of[0,n-1]){w.row(i);eq([...w.dx],Array.from({length:n},(_,j)=>j===i?Infinity:dist(x,i,j)));const order=Uint32Array.from(Array.from({length:n},(_,j)=>j).filter(j=>j!==i).sort((a,b)=>w.dx[a]-w.dx[b]||a-b));for(let q=0;q<order.length;q++)eq(w.rankX(order[q]),q+1);const hist=new Uint32Array(n);w.histX(order,n-1,hist,i);eq([...hist],Array.from({length:n},(_,j)=>j<n-1?1:0));}}
});
await group('RMCM exact/Float32 candidates, boundaries, batch tails and CSR filtering',()=>{
 for(const d of[1,3,8,17,32])for(const batch of[1,3,7]){const x=matrix(19,d),delta=dist(x,0,1),o={delta,graphBatchPairs:batch};const a=api.prepareRMCM(x,{...o,graphBackend:'wasm-simd'}),b=api.prepareRMCM(x,{...o,graphBackend:'scalar'});eq(a.neighborhoodMatrix(),b.neighborhoodMatrix());eq(a.degrees,b.degrees);const scanner=rmw.createRadiusScanner(x.data,19,d,delta,batch,1e7);ok(scanner);if(d>=8)eq(scanner.screening,'float32');else eq(scanner.exact,true);for(let i=0;i<19;i++)for(let start=i+1;start<19;start+=scanner.capacity){const end=Math.min(19,start+scanner.capacity),count=scanner.scan(i,start,end),ids=[...scanner.ids.subarray(0,count)];eq(ids,[...new Set(ids)].sort((a,b)=>a-b));for(let j=start;j<end;j++)if(dist(x,i,j)<=delta)ok(ids.includes(j));}}
 const n=7,d=3,x=matrix(n,d),reference={n,d,indptr:Uint32Array.from({length:n+1},(_,i)=>i*n),indices:Uint32Array.from({length:n*n},(_,i)=>i%n)};const a=rmw.createCsrFilter(x.data,reference,1.2,1e7),b=oldRm.createCsrFilter(x.data,reference,1.2,1e7);ok(a&&b);eq(a.filter(0,n),b.filter(0,n));eq(a.degrees,b.degrees);eq(a.keep,b.keep);
});
await group('Per-call ownership and workspace budget/unavailable-WASM fallbacks',()=>{
 eq(km.kmeansWasmWorkspace(20,8,3,7,0),null);eq(pcaw.pcaRotationWorkspace(32,1e6,0),null);eq(somw.somTrainingWorkspace(20,8,3,2,7,0,0),null);const x=matrix(13,8),y=matrix(13,2);eq(metric.wasmRows(x,y,0,3),null);eq(rmw.createRadiusScanner(x.data,13,8,1,7,0),null);
 const a=km.kmeansWasmWorkspace(20,8,3,7,1e7),b=km.kmeansWasmWorkspace(20,8,3,7,1e7);ok(a&&b);ok(a.labels.buffer!==b.labels.buffer);a.labels.fill(17);eq([...b.labels],Array(7).fill(0));
 const saved=globalThis.WebAssembly;try{globalThis.WebAssembly=undefined;eq(km.kmeansWasmWorkspace(20,8,3,7,1e7),null);eq(pcaw.pcaRotationWorkspace(32,1e7),null);eq(somw.somTrainingWorkspace(20,8,3,2,7,1e7,1e7),null);eq(metric.wasmRows(x,y,1e7,3),null);eq(rmw.createRadiusScanner(x.data,13,8,1,7,1e7),null);}finally{globalThis.WebAssembly=saved;}
});
}catch(e){failure=e;}
const report={schema_version:1,observed_utc:new Date().toISOString(),node:process.version,platform:process.platform,arch:process.arch,test_purpose:'Bounded deterministic correctness, ABI and fallback checks; no timing/performance claims or browser qualification',runtime:'isolated copy of the JavaScript package with exact rebuilt binaries',runtime_package_version:JSON.parse(fs.readFileSync(path.join(runtime,'package.json'))).version,seed:211859,passed:!failure,groups,checks:groups.reduce((s,g)=>s+g.checks,0),historical_test_lineage:['evidence/work/som_kmeans/tests/test_wasm_paths.mjs','evidence/work/rmcm/tests/f32-screening.test.js','evidence/work/rmcm/tests/rmcm-graph-parity.test.js'],limitations:['Finite cases do not prove all-input numerical equivalence.','Historical elite scalar runtime is not bundled or independently re-executed; scalar parity uses the current sibling package.','Only the recorded Node runtime was newly exercised.','Historical RMCM pre-Float32 and experimental nearest module receive ABI/byte checks but not separate numerical qualification.']};fs.writeFileSync(path.join(root,'verification/kernel-tests.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({passed:report.passed,groups:groups.length,checks:report.checks,failed:groups.find(g=>g.status==='failed')},null,2));if(failure)process.exitCode=1;
