(module
  (memory (export "memory") 1)
  ;; SIMD computes a conservative candidate set only. The JavaScript caller
  ;; reapplies its original left-to-right direct-distance predicate exactly.
  (func (export "scan")
    (param $base i32) (param $i i32) (param $start i32) (param $end i32)
    (param $d i32) (param $cutoff f64) (param $output i32)
    (result i32)
    (local $j i32) (local $f i32) (local $io i32) (local $jo i32)
    (local $count i32) (local $sum v128) (local $diff v128)
    (local $sq f64) (local $tail f64)
    (local.set $io (i32.add (local.get $base) (i32.mul (i32.mul (local.get $i) (local.get $d)) (i32.const 8))))
    (local.set $j (local.get $start))
    (block $endj
      (loop $loopj
        (br_if $endj (i32.ge_u (local.get $j) (local.get $end)))
        (local.set $jo (i32.add (local.get $base) (i32.mul (i32.mul (local.get $j) (local.get $d)) (i32.const 8))))
        (local.set $f (i32.const 0))
        (local.set $sum (v128.const f64x2 0 0))
        (block $endf
          (loop $loopf
            (br_if $endf (i32.ge_u (i32.add (local.get $f) (i32.const 1)) (local.get $d)))
            (local.set $diff (f64x2.sub
              (v128.load align=8 (i32.add (local.get $io) (i32.mul (local.get $f) (i32.const 8))))
              (v128.load align=8 (i32.add (local.get $jo) (i32.mul (local.get $f) (i32.const 8))))))
            (local.set $sum (f64x2.add (local.get $sum) (f64x2.mul (local.get $diff) (local.get $diff))))
            (local.set $f (i32.add (local.get $f) (i32.const 2)))
            (br $loopf)))
        (local.set $sq (f64.add (f64x2.extract_lane 0 (local.get $sum)) (f64x2.extract_lane 1 (local.get $sum))))
        (if (i32.lt_u (local.get $f) (local.get $d)) (then
          (local.set $tail (f64.sub
            (f64.load (i32.add (local.get $io) (i32.mul (local.get $f) (i32.const 8))))
            (f64.load (i32.add (local.get $jo) (i32.mul (local.get $f) (i32.const 8))))))
          (local.set $sq (f64.add (local.get $sq) (f64.mul (local.get $tail) (local.get $tail))))))
        (if (f64.le (local.get $sq) (local.get $cutoff)) (then
          (i32.store (i32.add (local.get $output) (i32.mul (local.get $count) (i32.const 4))) (local.get $j))
          (local.set $count (i32.add (local.get $count) (i32.const 1)))))
        (local.set $j (i32.add (local.get $j) (i32.const 1)))
        (br $loopj)))
    (local.get $count))
  (func (export "filter")
    (param $base i32) (param $d i32) (param $start i32) (param $end i32)
    (param $ptr i32) (param $ids i32) (param $degrees i32) (param $keep i32)
    (param $delta f64) (param $cutoff f64) (param $counter i32) (param $max_pairs i32) (result i32)
    (local $i i32) (local $j i32) (local $q i32) (local $qe i32) (local $f i32)
    (local $io i32) (local $jo i32) (local $deg i32) (local $nonzero i32)
    (local $diff f64) (local $sum f64)
    (local.set $i (local.get $start))
    (block $endi (loop $loopi
      (br_if $endi (i32.ge_u (local.get $i) (local.get $end)))
      (local.set $io (i32.add (local.get $base) (i32.mul (i32.mul (local.get $i) (local.get $d)) (i32.const 8))))
      (local.set $deg (i32.load (i32.add (local.get $degrees) (i32.mul (local.get $i) (i32.const 4)))))
      (local.set $q (i32.load (i32.add (local.get $ptr) (i32.mul (local.get $i) (i32.const 4)))))
      (local.set $qe (i32.load offset=4 (i32.add (local.get $ptr) (i32.mul (local.get $i) (i32.const 4)))))
      (block $endq (loop $loopq
        (br_if $endq (i32.ge_u (local.get $q) (local.get $qe)))
        (local.set $j (i32.load (i32.add (local.get $ids) (i32.mul (local.get $q) (i32.const 4)))))
        (block $pair_done
          (br_if $pair_done (i32.le_u (local.get $j) (local.get $i)))
          (local.set $jo (i32.add (local.get $base) (i32.mul (i32.mul (local.get $j) (local.get $d)) (i32.const 8))))
          (local.set $f (i32.const 0)) (local.set $sum (f64.const 0)) (local.set $nonzero (i32.const 0))
          (block $endf (loop $loopf
            (br_if $endf (i32.ge_u (local.get $f) (local.get $d)))
            (local.set $diff (f64.sub
              (f64.load (i32.add (local.get $io) (i32.mul (local.get $f) (i32.const 8))))
              (f64.load (i32.add (local.get $jo) (i32.mul (local.get $f) (i32.const 8))))))
            (local.set $nonzero (i32.or (local.get $nonzero) (f64.ne (local.get $diff) (f64.const 0))))
            (br_if $pair_done (i32.and (f64.eq (local.get $delta) (f64.const 0)) (local.get $nonzero)))
            (local.set $sum (f64.add (local.get $sum) (f64.mul (local.get $diff) (local.get $diff))))
            (br_if $pair_done (f64.gt (local.get $sum) (local.get $cutoff)))
            (local.set $f (i32.add (local.get $f) (i32.const 1))) (br $loopf)))
          (if (i32.and (f64.eq (local.get $sum) (f64.const 0)) (local.get $nonzero)) (then (return (i32.const -1))))
          (if (i32.and (f64.gt (local.get $sum) (f64.const 0)) (f64.lt (local.get $sum) (f64.const 2.2250738585072014e-308))) (then (return (i32.const -2))))
          (if (f64.le (f64.sqrt (local.get $sum)) (local.get $delta)) (then
            ;; Preserve the scalar edge-guard order before later numeric errors.
            (i32.store (local.get $counter) (i32.add (i32.load (local.get $counter)) (i32.const 1)))
            (if (i32.gt_u (i32.load (local.get $counter)) (local.get $max_pairs)) (then (return (i32.const -3))))
            (i32.store8 (i32.add (local.get $keep) (local.get $q)) (i32.const 1))
            (local.set $deg (i32.add (local.get $deg) (i32.const 1)))
            (i32.store (i32.add (local.get $degrees) (i32.mul (local.get $j) (i32.const 4)))
              (i32.add (i32.load (i32.add (local.get $degrees) (i32.mul (local.get $j) (i32.const 4)))) (i32.const 1))))))
        (local.set $q (i32.add (local.get $q) (i32.const 1))) (br $loopq)))
      (i32.store (i32.add (local.get $degrees) (i32.mul (local.get $i) (i32.const 4))) (local.get $deg))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $loopi)))
    (i32.const 0))

 (func $check_tiny (param $sq f64) (param $base i32) (param $i i32) (param $j i32) (param $n i32) (param $d i32) (result i32)
  (local $f i32) (local $off i32)
  (if (f64.gt (local.get $sq) (f64.const 0)) (then (return (i32.const -2))))
  (block $end (loop $loop
   (br_if $end (i32.ge_u (local.get $f) (local.get $d)))
   (local.set $off (i32.add (local.get $base) (i32.mul (i32.mul (local.get $f) (local.get $n)) (i32.const 8))))
   (if (f64.ne (f64.load (i32.add (local.get $off) (i32.mul (local.get $i) (i32.const 8)))) (f64.load (i32.add (local.get $off) (i32.mul (local.get $j) (i32.const 8)))))
    (then (return (i32.const -1))))
   (local.set $f (i32.add (local.get $f) (i32.const 1))) (br $loop)))
  (i32.const 0))
 (func (export "scan_exact")
  (param $base i32) (param $i i32) (param $n i32) (param $d i32)
  (param $start i32) (param $end i32) (param $delta f64) (param $out i32) (param $error i32) (result i32)
  (local $j i32) (local $f i32) (local $off i32) (local $count i32) (local $mask i32) (local $small i32) (local $code i32)
  (local $s0 v128) (local $s1 v128) (local $s2 v128) (local $s3 v128) (local $query v128) (local $diff v128)
  (local $sq f64) (local $tail f64)
  (i32.store (local.get $error) (i32.const 0))
  (local.set $j (local.get $start))
  (block $end_eight (loop $loop_eight
   (br_if $end_eight (i32.ge_u (i32.add (local.get $j) (i32.const 7)) (local.get $end)))
   (local.set $f (i32.const 0))
   (local.set $s0 (v128.const f64x2 0 0))
   (local.set $s1 (v128.const f64x2 0 0))
   (local.set $s2 (v128.const f64x2 0 0))
   (local.set $s3 (v128.const f64x2 0 0))
   (block $endf_eight (loop $loopf_eight
    (br_if $endf_eight (i32.ge_u (local.get $f) (local.get $d)))
    (local.set $off (i32.add (local.get $base) (i32.mul (i32.mul (local.get $f) (local.get $n)) (i32.const 8))))
    (local.set $query (f64x2.splat (f64.load (i32.add (local.get $off) (i32.mul (local.get $i) (i32.const 8))))))
    (local.set $diff (f64x2.sub (local.get $query) (v128.load offset=0 align=8 (i32.add (local.get $off) (i32.mul (local.get $j) (i32.const 8))))))
    (local.set $s0 (f64x2.add (local.get $s0) (f64x2.mul (local.get $diff) (local.get $diff))))
    (local.set $diff (f64x2.sub (local.get $query) (v128.load offset=16 align=8 (i32.add (local.get $off) (i32.mul (local.get $j) (i32.const 8))))))
    (local.set $s1 (f64x2.add (local.get $s1) (f64x2.mul (local.get $diff) (local.get $diff))))
    (local.set $diff (f64x2.sub (local.get $query) (v128.load offset=32 align=8 (i32.add (local.get $off) (i32.mul (local.get $j) (i32.const 8))))))
    (local.set $s2 (f64x2.add (local.get $s2) (f64x2.mul (local.get $diff) (local.get $diff))))
    (local.set $diff (f64x2.sub (local.get $query) (v128.load offset=48 align=8 (i32.add (local.get $off) (i32.mul (local.get $j) (i32.const 8))))))
    (local.set $s3 (f64x2.add (local.get $s3) (f64x2.mul (local.get $diff) (local.get $diff))))
    (local.set $f (i32.add (local.get $f) (i32.const 1))) (br $loopf_eight)))
   (local.set $mask (i64x2.bitmask (f64x2.le (f64x2.sqrt (local.get $s0)) (f64x2.splat (local.get $delta)))))
   (local.set $small (i64x2.bitmask (f64x2.lt (local.get $s0) (f64x2.splat (f64.const 2.2250738585072014e-308)))))
   (if (local.get $small) (then
    (if (i32.and (local.get $small) (i32.const 1)) (then (local.set $code (call $check_tiny (f64x2.extract_lane 0 (local.get $s0)) (local.get $base) (local.get $i) (i32.add (local.get $j) (i32.const 0)) (local.get $n) (local.get $d)))
          (if (local.get $code) (then (i32.store (local.get $error) (local.get $code)) (return (local.get $count))))))
    (if (i32.and (local.get $mask) (i32.const 1)) (then (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 0)))
          (local.set $count (i32.add (local.get $count) (i32.const 1)))))
    (if (i32.and (local.get $small) (i32.const 2)) (then (local.set $code (call $check_tiny (f64x2.extract_lane 1 (local.get $s0)) (local.get $base) (local.get $i) (i32.add (local.get $j) (i32.const 1)) (local.get $n) (local.get $d)))
          (if (local.get $code) (then (i32.store (local.get $error) (local.get $code)) (return (local.get $count))))))
    (if (i32.and (local.get $mask) (i32.const 2)) (then (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 1)))
          (local.set $count (i32.add (local.get $count) (i32.const 1))))))
   (else
    (if (i32.and (local.get $mask) (i32.const 1)) (then (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 0)))
          (local.set $count (i32.add (local.get $count) (i32.const 1)))))
    (if (i32.and (local.get $mask) (i32.const 2)) (then (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 1)))
          (local.set $count (i32.add (local.get $count) (i32.const 1)))))))
   (local.set $mask (i64x2.bitmask (f64x2.le (f64x2.sqrt (local.get $s1)) (f64x2.splat (local.get $delta)))))
   (local.set $small (i64x2.bitmask (f64x2.lt (local.get $s1) (f64x2.splat (f64.const 2.2250738585072014e-308)))))
   (if (local.get $small) (then
    (if (i32.and (local.get $small) (i32.const 1)) (then (local.set $code (call $check_tiny (f64x2.extract_lane 0 (local.get $s1)) (local.get $base) (local.get $i) (i32.add (local.get $j) (i32.const 2)) (local.get $n) (local.get $d)))
          (if (local.get $code) (then (i32.store (local.get $error) (local.get $code)) (return (local.get $count))))))
    (if (i32.and (local.get $mask) (i32.const 1)) (then (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 2)))
          (local.set $count (i32.add (local.get $count) (i32.const 1)))))
    (if (i32.and (local.get $small) (i32.const 2)) (then (local.set $code (call $check_tiny (f64x2.extract_lane 1 (local.get $s1)) (local.get $base) (local.get $i) (i32.add (local.get $j) (i32.const 3)) (local.get $n) (local.get $d)))
          (if (local.get $code) (then (i32.store (local.get $error) (local.get $code)) (return (local.get $count))))))
    (if (i32.and (local.get $mask) (i32.const 2)) (then (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 3)))
          (local.set $count (i32.add (local.get $count) (i32.const 1))))))
   (else
    (if (i32.and (local.get $mask) (i32.const 1)) (then (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 2)))
          (local.set $count (i32.add (local.get $count) (i32.const 1)))))
    (if (i32.and (local.get $mask) (i32.const 2)) (then (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 3)))
          (local.set $count (i32.add (local.get $count) (i32.const 1)))))))
   (local.set $mask (i64x2.bitmask (f64x2.le (f64x2.sqrt (local.get $s2)) (f64x2.splat (local.get $delta)))))
   (local.set $small (i64x2.bitmask (f64x2.lt (local.get $s2) (f64x2.splat (f64.const 2.2250738585072014e-308)))))
   (if (local.get $small) (then
    (if (i32.and (local.get $small) (i32.const 1)) (then (local.set $code (call $check_tiny (f64x2.extract_lane 0 (local.get $s2)) (local.get $base) (local.get $i) (i32.add (local.get $j) (i32.const 4)) (local.get $n) (local.get $d)))
          (if (local.get $code) (then (i32.store (local.get $error) (local.get $code)) (return (local.get $count))))))
    (if (i32.and (local.get $mask) (i32.const 1)) (then (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 4)))
          (local.set $count (i32.add (local.get $count) (i32.const 1)))))
    (if (i32.and (local.get $small) (i32.const 2)) (then (local.set $code (call $check_tiny (f64x2.extract_lane 1 (local.get $s2)) (local.get $base) (local.get $i) (i32.add (local.get $j) (i32.const 5)) (local.get $n) (local.get $d)))
          (if (local.get $code) (then (i32.store (local.get $error) (local.get $code)) (return (local.get $count))))))
    (if (i32.and (local.get $mask) (i32.const 2)) (then (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 5)))
          (local.set $count (i32.add (local.get $count) (i32.const 1))))))
   (else
    (if (i32.and (local.get $mask) (i32.const 1)) (then (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 4)))
          (local.set $count (i32.add (local.get $count) (i32.const 1)))))
    (if (i32.and (local.get $mask) (i32.const 2)) (then (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 5)))
          (local.set $count (i32.add (local.get $count) (i32.const 1)))))))
   (local.set $mask (i64x2.bitmask (f64x2.le (f64x2.sqrt (local.get $s3)) (f64x2.splat (local.get $delta)))))
   (local.set $small (i64x2.bitmask (f64x2.lt (local.get $s3) (f64x2.splat (f64.const 2.2250738585072014e-308)))))
   (if (local.get $small) (then
    (if (i32.and (local.get $small) (i32.const 1)) (then (local.set $code (call $check_tiny (f64x2.extract_lane 0 (local.get $s3)) (local.get $base) (local.get $i) (i32.add (local.get $j) (i32.const 6)) (local.get $n) (local.get $d)))
          (if (local.get $code) (then (i32.store (local.get $error) (local.get $code)) (return (local.get $count))))))
    (if (i32.and (local.get $mask) (i32.const 1)) (then (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 6)))
          (local.set $count (i32.add (local.get $count) (i32.const 1)))))
    (if (i32.and (local.get $small) (i32.const 2)) (then (local.set $code (call $check_tiny (f64x2.extract_lane 1 (local.get $s3)) (local.get $base) (local.get $i) (i32.add (local.get $j) (i32.const 7)) (local.get $n) (local.get $d)))
          (if (local.get $code) (then (i32.store (local.get $error) (local.get $code)) (return (local.get $count))))))
    (if (i32.and (local.get $mask) (i32.const 2)) (then (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 7)))
          (local.set $count (i32.add (local.get $count) (i32.const 1))))))
   (else
    (if (i32.and (local.get $mask) (i32.const 1)) (then (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 6)))
          (local.set $count (i32.add (local.get $count) (i32.const 1)))))
    (if (i32.and (local.get $mask) (i32.const 2)) (then (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 7)))
          (local.set $count (i32.add (local.get $count) (i32.const 1)))))))
   (local.set $j (i32.add (local.get $j) (i32.const 8))) (br $loop_eight)))
  (block $end_two (loop $loop_two
   (br_if $end_two (i32.ge_u (i32.add (local.get $j) (i32.const 1)) (local.get $end)))
   (local.set $f (i32.const 0))
   (local.set $s0 (v128.const f64x2 0 0))
   (block $endf_two (loop $loopf_two
    (br_if $endf_two (i32.ge_u (local.get $f) (local.get $d)))
    (local.set $off (i32.add (local.get $base) (i32.mul (i32.mul (local.get $f) (local.get $n)) (i32.const 8))))
    (local.set $query (f64x2.splat (f64.load (i32.add (local.get $off) (i32.mul (local.get $i) (i32.const 8))))))
    (local.set $diff (f64x2.sub (local.get $query) (v128.load offset=0 align=8 (i32.add (local.get $off) (i32.mul (local.get $j) (i32.const 8))))))
    (local.set $s0 (f64x2.add (local.get $s0) (f64x2.mul (local.get $diff) (local.get $diff))))
    (local.set $f (i32.add (local.get $f) (i32.const 1))) (br $loopf_two)))
   (local.set $mask (i64x2.bitmask (f64x2.le (f64x2.sqrt (local.get $s0)) (f64x2.splat (local.get $delta)))))
   (local.set $small (i64x2.bitmask (f64x2.lt (local.get $s0) (f64x2.splat (f64.const 2.2250738585072014e-308)))))
   (if (local.get $small) (then
    (if (i32.and (local.get $small) (i32.const 1)) (then (local.set $code (call $check_tiny (f64x2.extract_lane 0 (local.get $s0)) (local.get $base) (local.get $i) (i32.add (local.get $j) (i32.const 0)) (local.get $n) (local.get $d)))
          (if (local.get $code) (then (i32.store (local.get $error) (local.get $code)) (return (local.get $count))))))
    (if (i32.and (local.get $mask) (i32.const 1)) (then (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 0)))
          (local.set $count (i32.add (local.get $count) (i32.const 1)))))
    (if (i32.and (local.get $small) (i32.const 2)) (then (local.set $code (call $check_tiny (f64x2.extract_lane 1 (local.get $s0)) (local.get $base) (local.get $i) (i32.add (local.get $j) (i32.const 1)) (local.get $n) (local.get $d)))
          (if (local.get $code) (then (i32.store (local.get $error) (local.get $code)) (return (local.get $count))))))
    (if (i32.and (local.get $mask) (i32.const 2)) (then (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 1)))
          (local.set $count (i32.add (local.get $count) (i32.const 1))))))
   (else
    (if (i32.and (local.get $mask) (i32.const 1)) (then (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 0)))
          (local.set $count (i32.add (local.get $count) (i32.const 1)))))
    (if (i32.and (local.get $mask) (i32.const 2)) (then (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 1)))
          (local.set $count (i32.add (local.get $count) (i32.const 1)))))))
   (local.set $j (i32.add (local.get $j) (i32.const 2))) (br $loop_two)))

  (if (i32.lt_u (local.get $j) (local.get $end)) (then
   (local.set $f (i32.const 0)) (local.set $sq (f64.const 0))
   (block $endtail (loop $tail_loop
    (br_if $endtail (i32.ge_u (local.get $f) (local.get $d)))
    (local.set $off (i32.add (local.get $base) (i32.mul (i32.mul (local.get $f) (local.get $n)) (i32.const 8))))
    (local.set $tail (f64.sub (f64.load (i32.add (local.get $off) (i32.mul (local.get $i) (i32.const 8)))) (f64.load (i32.add (local.get $off) (i32.mul (local.get $j) (i32.const 8))))))
    (local.set $sq (f64.add (local.get $sq) (f64.mul (local.get $tail) (local.get $tail))))
    (local.set $f (i32.add (local.get $f) (i32.const 1))) (br $tail_loop)))
   (if (f64.lt (local.get $sq) (f64.const 2.2250738585072014e-308)) (then
    (local.set $code (call $check_tiny (local.get $sq) (local.get $base) (local.get $i) (local.get $j) (local.get $n) (local.get $d)))
    (if (local.get $code) (then (i32.store (local.get $error) (local.get $code)) (return (local.get $count))))))
   (if (f64.le (f64.sqrt (local.get $sq)) (local.get $delta)) (then
    (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (local.get $j))
    (local.set $count (i32.add (local.get $count) (i32.const 1)))))))
  (local.get $count))
 (func (export "scan_f32_candidates")
  (param $base i32) (param $i i32) (param $n i32) (param $d i32)
  (param $start i32) (param $end i32) (param $cutoff f32) (param $out i32) (result i32)
  (local $j i32) (local $f i32) (local $off i32) (local $count i32) (local $mask i32)
  (local $s0 v128) (local $s1 v128) (local $s2 v128) (local $s3 v128) (local $query v128) (local $diff v128)
  (local $sq f32) (local $tail f32)
  (local.set $j (local.get $start))
  (block $end_p16 (loop $loop_p16
   (br_if $end_p16 (i32.ge_u (i32.add (local.get $j) (i32.const 15)) (local.get $end)))
   (local.set $f (i32.const 0))
   (local.set $s0 (v128.const f32x4 0 0 0 0))
   (local.set $s1 (v128.const f32x4 0 0 0 0))
   (local.set $s2 (v128.const f32x4 0 0 0 0))
   (local.set $s3 (v128.const f32x4 0 0 0 0))
   (block $endf_p16 (loop $loopf_p16
    (br_if $endf_p16 (i32.ge_u (local.get $f) (local.get $d)))
    (local.set $off (i32.add (local.get $base) (i32.mul (i32.mul (local.get $f) (local.get $n)) (i32.const 4))))
    (local.set $query (f32x4.splat (f32.load (i32.add (local.get $off) (i32.mul (local.get $i) (i32.const 4))))))
    (local.set $diff (f32x4.sub (local.get $query) (v128.load offset=0 align=4 (i32.add (local.get $off) (i32.mul (local.get $j) (i32.const 4))))))
    (local.set $s0 (f32x4.add (local.get $s0) (f32x4.mul (local.get $diff) (local.get $diff))))
    (local.set $diff (f32x4.sub (local.get $query) (v128.load offset=16 align=4 (i32.add (local.get $off) (i32.mul (local.get $j) (i32.const 4))))))
    (local.set $s1 (f32x4.add (local.get $s1) (f32x4.mul (local.get $diff) (local.get $diff))))
    (local.set $diff (f32x4.sub (local.get $query) (v128.load offset=32 align=4 (i32.add (local.get $off) (i32.mul (local.get $j) (i32.const 4))))))
    (local.set $s2 (f32x4.add (local.get $s2) (f32x4.mul (local.get $diff) (local.get $diff))))
    (local.set $diff (f32x4.sub (local.get $query) (v128.load offset=48 align=4 (i32.add (local.get $off) (i32.mul (local.get $j) (i32.const 4))))))
    (local.set $s3 (f32x4.add (local.get $s3) (f32x4.mul (local.get $diff) (local.get $diff))))
    (local.set $f (i32.add (local.get $f) (i32.const 1)))
    (if (i32.eqz (i32.and (local.get $f) (i32.const 7))) (then (br_if $endf_p16 (i8x16.all_true (v128.and (v128.and (v128.and (f32x4.gt (local.get $s0) (f32x4.splat (local.get $cutoff))) (f32x4.gt (local.get $s1) (f32x4.splat (local.get $cutoff)))) (f32x4.gt (local.get $s2) (f32x4.splat (local.get $cutoff)))) (f32x4.gt (local.get $s3) (f32x4.splat (local.get $cutoff))))))))
    (br $loopf_p16)))
   (local.set $mask (i32x4.bitmask (f32x4.le (local.get $s0) (f32x4.splat (local.get $cutoff)))))
   (if (i32.and (local.get $mask) (i32.const 1)) (then
    (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 0)))
    (local.set $count (i32.add (local.get $count) (i32.const 1)))))
   (if (i32.and (local.get $mask) (i32.const 2)) (then
    (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 1)))
    (local.set $count (i32.add (local.get $count) (i32.const 1)))))
   (if (i32.and (local.get $mask) (i32.const 4)) (then
    (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 2)))
    (local.set $count (i32.add (local.get $count) (i32.const 1)))))
   (if (i32.and (local.get $mask) (i32.const 8)) (then
    (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 3)))
    (local.set $count (i32.add (local.get $count) (i32.const 1)))))
   (local.set $mask (i32x4.bitmask (f32x4.le (local.get $s1) (f32x4.splat (local.get $cutoff)))))
   (if (i32.and (local.get $mask) (i32.const 1)) (then
    (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 4)))
    (local.set $count (i32.add (local.get $count) (i32.const 1)))))
   (if (i32.and (local.get $mask) (i32.const 2)) (then
    (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 5)))
    (local.set $count (i32.add (local.get $count) (i32.const 1)))))
   (if (i32.and (local.get $mask) (i32.const 4)) (then
    (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 6)))
    (local.set $count (i32.add (local.get $count) (i32.const 1)))))
   (if (i32.and (local.get $mask) (i32.const 8)) (then
    (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 7)))
    (local.set $count (i32.add (local.get $count) (i32.const 1)))))
   (local.set $mask (i32x4.bitmask (f32x4.le (local.get $s2) (f32x4.splat (local.get $cutoff)))))
   (if (i32.and (local.get $mask) (i32.const 1)) (then
    (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 8)))
    (local.set $count (i32.add (local.get $count) (i32.const 1)))))
   (if (i32.and (local.get $mask) (i32.const 2)) (then
    (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 9)))
    (local.set $count (i32.add (local.get $count) (i32.const 1)))))
   (if (i32.and (local.get $mask) (i32.const 4)) (then
    (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 10)))
    (local.set $count (i32.add (local.get $count) (i32.const 1)))))
   (if (i32.and (local.get $mask) (i32.const 8)) (then
    (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 11)))
    (local.set $count (i32.add (local.get $count) (i32.const 1)))))
   (local.set $mask (i32x4.bitmask (f32x4.le (local.get $s3) (f32x4.splat (local.get $cutoff)))))
   (if (i32.and (local.get $mask) (i32.const 1)) (then
    (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 12)))
    (local.set $count (i32.add (local.get $count) (i32.const 1)))))
   (if (i32.and (local.get $mask) (i32.const 2)) (then
    (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 13)))
    (local.set $count (i32.add (local.get $count) (i32.const 1)))))
   (if (i32.and (local.get $mask) (i32.const 4)) (then
    (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 14)))
    (local.set $count (i32.add (local.get $count) (i32.const 1)))))
   (if (i32.and (local.get $mask) (i32.const 8)) (then
    (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 15)))
    (local.set $count (i32.add (local.get $count) (i32.const 1)))))
   (local.set $j (i32.add (local.get $j) (i32.const 16)))
   (br $loop_p16)))
  (block $end_p4 (loop $loop_p4
   (br_if $end_p4 (i32.ge_u (i32.add (local.get $j) (i32.const 3)) (local.get $end)))
   (local.set $f (i32.const 0))
   (local.set $s0 (v128.const f32x4 0 0 0 0))
   (block $endf_p4 (loop $loopf_p4
    (br_if $endf_p4 (i32.ge_u (local.get $f) (local.get $d)))
    (local.set $off (i32.add (local.get $base) (i32.mul (i32.mul (local.get $f) (local.get $n)) (i32.const 4))))
    (local.set $query (f32x4.splat (f32.load (i32.add (local.get $off) (i32.mul (local.get $i) (i32.const 4))))))
    (local.set $diff (f32x4.sub (local.get $query) (v128.load offset=0 align=4 (i32.add (local.get $off) (i32.mul (local.get $j) (i32.const 4))))))
    (local.set $s0 (f32x4.add (local.get $s0) (f32x4.mul (local.get $diff) (local.get $diff))))
    (local.set $f (i32.add (local.get $f) (i32.const 1)))
    (if (i32.eqz (i32.and (local.get $f) (i32.const 7))) (then (br_if $endf_p4 (i8x16.all_true (f32x4.gt (local.get $s0) (f32x4.splat (local.get $cutoff)))))))
    (br $loopf_p4)))
   (local.set $mask (i32x4.bitmask (f32x4.le (local.get $s0) (f32x4.splat (local.get $cutoff)))))
   (if (i32.and (local.get $mask) (i32.const 1)) (then
    (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 0)))
    (local.set $count (i32.add (local.get $count) (i32.const 1)))))
   (if (i32.and (local.get $mask) (i32.const 2)) (then
    (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 1)))
    (local.set $count (i32.add (local.get $count) (i32.const 1)))))
   (if (i32.and (local.get $mask) (i32.const 4)) (then
    (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 2)))
    (local.set $count (i32.add (local.get $count) (i32.const 1)))))
   (if (i32.and (local.get $mask) (i32.const 8)) (then
    (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (i32.add (local.get $j) (i32.const 3)))
    (local.set $count (i32.add (local.get $count) (i32.const 1)))))
   (local.set $j (i32.add (local.get $j) (i32.const 4)))
   (br $loop_p4)))
  (block $end_tail (loop $loop_tail
   (br_if $end_tail (i32.ge_u (local.get $j) (local.get $end)))
   (local.set $f (i32.const 0)) (local.set $sq (f32.const 0))
   (block $endf_tail (loop $loopf_tail
    (br_if $endf_tail (i32.ge_u (local.get $f) (local.get $d)))
    (local.set $off (i32.add (local.get $base) (i32.mul (i32.mul (local.get $f) (local.get $n)) (i32.const 4))))
    (local.set $tail (f32.sub (f32.load (i32.add (local.get $off) (i32.mul (local.get $i) (i32.const 4)))) (f32.load (i32.add (local.get $off) (i32.mul (local.get $j) (i32.const 4))))))
    (local.set $sq (f32.add (local.get $sq) (f32.mul (local.get $tail) (local.get $tail))))
    (br_if $endf_tail (f32.gt (local.get $sq) (local.get $cutoff)))
    (local.set $f (i32.add (local.get $f) (i32.const 1))) (br $loopf_tail)))
   (if (f32.le (local.get $sq) (local.get $cutoff)) (then
    (i32.store (i32.add (local.get $out) (i32.mul (local.get $count) (i32.const 4))) (local.get $j))
    (local.set $count (i32.add (local.get $count) (i32.const 1)))))
   (local.set $j (i32.add (local.get $j) (i32.const 1))) (br $loop_tail)))
  (local.get $count))
)
