import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createHash} from 'node:crypto';
import * as candidate from '../../consumer/node_modules/ubukit-js/src/index.js';
import * as baseline from '../efficiency_baseline_package/src/index.js';
import {squaredDistance} from '../efficiency_baseline_package/src/core.js';
import {nearestCenter2d,nearestCenterGrouped} from '../../consumer/node_modules/ubukit-js/src/iteration-kernels.js';
import {kmeansSteps as newSteps} from '../../consumer/node_modules/ubukit-js/src/clustering.js';
import {kmeansSteps as oldSteps} from '../efficiency_baseline_package/src/clustering.js';
import {SESSION_CHECKPOINT as newHook} from '../../consumer/node_modules/ubukit-js/src/session-hooks.js';
import {SESSION_CHECKPOINT as oldHook} from '../efficiency_baseline_package/src/session-hooks.js';
const report={started:new Date().toISOString(),groups:[],failures:[],cases:0};
function check(name,fn){try{const n=fn()??1;report.cases+=n;report.groups.push({name,status:'passed',cases:n});}catch(e){report.failures.push({name,message:e.message,stack:e.stack});report.groups.push({name,status:'failed'});}}
function capture(fn){try{return {value:fn()};}catch(e){return {name:e.name,message:e.message};}}
function rng(seed=7){return()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};}
function data(n,d,seed=7){const r=rng(seed);return{data:Float64Array.from({length:n*d},()=>4*r()-2),nSamples:n,nFeatures:d};}
function scalar(x,offset,w,d,k){let best=0,bd=Infinity;for(let j=0;j<k;j++){const dist=squaredDistance(x,offset,w,j*d,d,bd);if(dist<bd){best=j;bd=dist;}}return best;}
check('BMU finite values, nonzero offsets, feature/center tails and first ties',()=>{let n=0;for(const d of [...Array.from({length:40},(_,i)=>i+1),63,64,65,129])for(const k of [1,2,3,4,5,7,8,9,15,16,17,33]){const x=data(5,d),w=data(k,d,33).data;for(let i=0;i<5;i++){assert.equal(nearestCenterGrouped(x.data,i*d,w,d,k),scalar(x.data,i*d,w,d,k));n++;if(d===2){assert.equal(nearestCenter2d(x.data,i*d,w,d,k),scalar(x.data,i*d,w,d,k));n++;}}w.fill(0);assert.equal(nearestCenterGrouped(new Float64Array(d),0,w,d,k),0);n++;}return n;});
check('BMU strict exception/cutoff oracle across extreme finite exponents',()=>{let n=0;const a=[0,-0,Number.MIN_VALUE,-Number.MIN_VALUE,1e-200,-1e-200,1e-162,1e-160,1e-154,1.4916681462400413e-154,1e-100,1,-1,1e100,1e154,-1e154,1e155,Number.MAX_VALUE,-Number.MAX_VALUE];const r=rng(990);for(const d of [1,2,3,4,5,7,8,9,15,16,17,33])for(let t=0;t<900;t++){const k=1+t%19,x=new Float64Array(d+3),w=new Float64Array(k*d);for(let f=0;f<d;f++)x[f+3]=a[Math.floor(r()*a.length)];for(let z=0;z<w.length;z++)w[z]=a[Math.floor(r()*a.length)];const e=capture(()=>scalar(x,3,w,d,k));assert.deepEqual(capture(()=>nearestCenterGrouped(x,3,w,d,k)),e,`D${d} K${k} trial${t}`);n++;if(d===2){assert.deepEqual(capture(()=>nearestCenter2d(x,3,w,d,k)),e);n++;}}return n;});
check('Complete SOM outputs exact against frozen dev5, all selectors and K threshold',()=>{let n=0;for(const algorithm of ['som','som_batch'])for(const d of [1,2,3,4,5,8,17])for(const k of [1,3,4,15,16,17]){const x=data(23,d),o={gridShape:[k,1],initialPrototypes:data(k,d,84).data,maxIterations:algorithm==='som'?11:3,blockRows:4,blockUnits:3};const e=baseline.run(algorithm,x,o);for(const bmuBackend of ['scalar','grouped','auto']){assert.deepEqual(candidate.run(algorithm,x,{...o,bmuBackend}),e,`${algorithm} D${d} K${k} ${bmuBackend}`);n++;}}return n;});
check('Complete KMeans WASM outputs and workspace size exact frozen dev5',()=>{let n=0;for(const d of [1,2,3,4,5,8,17,33])for(const k of [1,3,4,5,15,16,17])for(const blockRows of [1,7,511]){const x=data(29,d),o={nClusters:k,initCenters:data(k,d,27).data,maxIterations:4,blockRows,kernelBackend:'wasm'};const e=baseline.run('kmeans',x,o);for(const wasmCenterCache of [true,false]){assert.deepEqual(candidate.run('kmeans',x,{...o,wasmCenterCache}),e);n++;}}return n;});
function mutationTrace(steps,hook,{late=false}={}){const x=data(17,3,12),o={nClusters:4,initCenters:data(4,3,32).data,maxIterations:3,blockRows:2,kernelBackend:'wasm'},events=[];let live=null,index=0;const callback=s=>{live=s.centers;};if(!late)o[hook]=callback;const iter=steps(x,o);for(;;){const v=iter.next();if(v.done)return{events,result:v.value};events.push(structuredClone(v.value));index++;if(late&&index===1)o[hook]=callback;if(live){live[index%live.length]+=.75;}}}
check('Retained mutable checkpoint centers across assignment/finalization yields',()=>{assert.deepEqual(mutationTrace(newSteps,newHook),mutationTrace(oldSteps,oldHook));});
check('Callback installed after iterator start, then retains mutable centers',()=>{assert.deepEqual(mutationTrace(newSteps,newHook,{late:true}),mutationTrace(oldSteps,oldHook,{late:true}));});
function finish(s){let n=0;while(!s.status.done){s.step(1,{timeBudgetMs:0,maxChunks:1});assert.ok(++n<50000);}return s.snapshot();}
check('Sessions own inputs, discard stale chunks and reject parameter changes atomically',()=>{let n=0;for(const algorithm of ['kmeans','som','som_batch']){const x=data(27,2),o=algorithm==='kmeans'?{nClusters:5,maxIterations:3,kernelBackend:'wasm',blockRows:3}:{gridShape:[4,4],maxIterations:3,blockRows:3,blockUnits:3};const a=candidate.createSession(algorithm,x,o),b=baseline.createSession(algorithm,x,o);x.data.fill(777);for(let i=0;i<8;i++){a.step(1,{maxChunks:1,timeBudgetMs:0});b.step(1,{maxChunks:1,timeBudgetMs:0});}const x2=data(21,2,333);a.updateData(x2,{warmStart:false});b.updateData(x2,{warmStart:false});x2.data.fill(888);assert.deepEqual(finish(a),finish(b));if(algorithm!=='kmeans')assert.deepEqual(a.snapshot({project:true}),b.snapshot({project:true}));const snap=a.snapshot();if(snap.result?.centers)snap.result.centers.fill(999);assert.deepEqual(a.snapshot(),b.snapshot());const before=a.snapshot();assert.throws(()=>a.updateParameters(algorithm==='kmeans'?{wasmCenterCache:3}:{bmuBackend:'bad'}));assert.deepEqual(a.snapshot(),before);n++;}return n;});
check('Elite module routing preserves malformed-header and numeric validation errors',()=>{let n=0;for(const algorithm of ['som','som_batch'])for(const d of [2,9])for(const shape of [null,[1n,16],[2,3n],[0,3],[-1,16],[2.5,3],[NaN,2],[Infinity,2],[2147483648,1],[2],new DataView(new ArrayBuffer(16)),[4,4],[3,3]]){const x=data(7,d),o={gridShape:shape,maxIterations:0};assert.deepEqual(capture(()=>candidate.run(algorithm,x,o)),capture(()=>baseline.run(algorithm,x,o)));n++;}return n;});
report.status=report.failures.length?'failed':'passed';report.finished=new Date().toISOString();
report.runtimeFiles=['som.js','som-elite.js','iteration-kernels.js','kmeans-wasm.js','clustering.js','session.js','session-validation.js'].map(path=>({path,sha256:createHash('sha256').update(fs.readFileSync(new URL('../../consumer/node_modules/ubukit-js/src/'+path,import.meta.url))).digest('hex')}));
console.log(JSON.stringify(report,null,2));process.exitCode=report.failures.length?1:0;
