import { createWorkerClient, seededRandom } from '../../javascript/src/index.js';
const $=id=>document.getElementById(id), client=createWorkerClient();
let sample, result, seed=7, controller, ticks=0;
setInterval(()=>{$('heartbeat').innerHTML=`<span class="dot"></span>UI heartbeat ${++ticks}`;},100);
function generate(){const n=Number($('count').value);if(!Number.isInteger(n)||n<30||n>10000)throw new RangeError('データ数は30〜10000にしてください');const random=seededRandom(seed),data=new Float64Array(n*2);for(let i=0;i<n;i++){const c=i%4,a=2*Math.PI*random(),r=Math.sqrt(-2*Math.log(Math.max(random(),1e-12)))*.52;data[i*2]=(c%2)*4+r*Math.cos(a);data[i*2+1]=Math.floor(c/2)*4+r*Math.sin(a);}sample={data,nSamples:n,nFeatures:2};result=null;draw();}
function draw(){const canvas=$('plot'),ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);const data=result?.embedding??sample.data,dims=result?.nComponents??2;const n=sample.nSamples;let minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity;for(let i=0;i<n;i++){minX=Math.min(minX,data[i*dims]);maxX=Math.max(maxX,data[i*dims]);minY=Math.min(minY,data[i*dims+1]);maxY=Math.max(maxY,data[i*dims+1]);}const xy=(x,y)=>[24+(x-minX)/(maxX-minX||1)*(canvas.width-48),canvas.height-24-(y-minY)/(maxY-minY||1)*(canvas.height-48)];const colors=['#187b61','#ec9b38','#5a70bf','#cf6370','#8d66ad','#50a4a5'];for(let i=0;i<n;i++){const [x,y]=xy(data[i*dims],data[i*dims+1]);ctx.fillStyle=result?.labels?colors[result.labels[i]%colors.length]:'#719e85';ctx.globalAlpha=.65;ctx.beginPath();ctx.arc(x,y,2.7,0,2*Math.PI);ctx.fill();}ctx.globalAlpha=1;if(result?.centers&&!result.embedding){ctx.strokeStyle='#17382e';ctx.lineWidth=2;for(let i=0;i<result.centers.length;i+=2){const[x,y]=xy(result.centers[i],result.centers[i+1]);ctx.strokeRect(x-6,y-6,12,12);}}}
function grid(){const data=new Float64Array(72);for(let j=0;j<36;j++){data[j*2]=j%6/5;data[j*2+1]=Math.floor(j/6)/5;}return {data,nSamples:36,nFeatures:2};}
$('new').onclick=()=>{try{seed++;generate();$('status').textContent='データを再生成しました';}catch(e){$('status').textContent=e.message;}};
$('run').onclick=async()=>{if(client.busy)return;try{if(sample.nSamples!==Number($('count').value))generate();const algorithm=$('algorithm').value;controller=new AbortController();$('run').disabled=true;$('new').disabled=true;$('cancel').disabled=false;$('status').textContent='計算中…';const started=performance.now();const options={nClusters:4,seed:7,maxIterations:60,alpha:1.15,beta:.1,p:algorithm==='exrcm'?2:1,signal:controller.signal,onProgress:event=>{$('status').textContent=`計算中 · ${event.iteration?`反復 ${event.iteration}`:`${event.completed??0}/${event.total??sample.nSamples} 行`}`;}};if(algorithm==='som-olp')Object.assign(options,{grid:grid(),initializer:'pca',gamma:1,lambda:.1});if(algorithm==='neighborhood'){const embedding=sample.data.slice();for(let i=0;i<sample.nSamples;i++){embedding[i*2]=Math.tanh(embedding[i*2]);embedding[i*2+1]=Math.tanh(embedding[i*2+1]);}Object.assign(options,{embedding:{...sample,data:embedding},k:10});}result=await client.run(algorithm,sample,options);const elapsed=performance.now()-started;$('status').textContent=`完了 · ${elapsed.toFixed(1)} ms (Worker通信込み)`;$('details').textContent=JSON.stringify({algorithm,iterations:result.iterations,converged:result.converged,objective:result.objective,qualities:result.qualities,stats:result.stats},null,2);draw();}catch(error){$('status').textContent=error.name==='AbortError'?'キャンセルしました':error.message;}finally{$('run').disabled=false;$('new').disabled=false;$('cancel').disabled=true;}};
$('cancel').onclick=()=>controller?.abort();window.addEventListener('pagehide',()=>client.dispose());generate();
