import { performance } from 'node:perf_hooks';
import { run, seededRandom } from '../src/index.js';
import assert from 'node:assert/strict';
import { referenceFcmLinear } from './fcm-linear-reference.js';
function matrix(a,n,d){return Array.from({length:n},(_,i)=>Array.from(a.subarray(i*d,(i+1)*d)));}
function distance(a,b){let s=0;for(let f=0;f<a.length;f++){const v=a[f]-b[f];s+=v*v;}return s;}
/** Readable scratch baselines. FCM uses a separate fair O(NK) TypedArray reference. */
function scratch(algorithm,input,options){if(algorithm==='fcm')return referenceFcmLinear(input,options);const x=matrix(input.data,input.nSamples,input.nFeatures),n=x.length,d=x[0].length,k=options.nClusters;let c=matrix(options.initCenters,k,d),u=null;let prev=null,iter=0;for(iter=1;iter<=options.maxIterations;iter++){const dist=x.map(row=>c.map(center=>distance(row,center)));u=dist.map(row=>{if(algorithm==='kmeans'){const m=Math.min(...row);const first=row.indexOf(m);return row.map((_,j)=>j===first?1:0);}const euclidean=row.map(Math.sqrt),minimum=Math.min(...euclidean);const mask=euclidean.map(v=>v**options.p<=options.alpha**options.p*minimum**options.p+options.beta**options.p?1:0);const sum=mask.reduce((a,b)=>a+b,0);return mask.map(v=>v/sum);});const equal=prev&&u.every((row,i)=>row.every((v,j)=>v===prev[i][j]));prev=u;c=c.map((old,j)=>{const sum=u.reduce((a,row)=>a+row[j],0);return sum?Array.from({length:d},(_,f)=>x.reduce((a,row,i)=>a+u[i][j]*row[f],0)/sum):old;});if(equal)break;}
const centers=Float64Array.from(c.flat());if(algorithm==='kmeans'){const labels=Int32Array.from(x,row=>{const dd=c.map(center=>distance(row,center));return dd.indexOf(Math.min(...dd));});const inertia=x.reduce((sum,row,i)=>sum+distance(row,c[labels[i]]),0);return {centers,labels,inertia,iterations:Math.min(iter,options.maxIterations)};}
u=x.map(row=>{const dd=c.map(center=>Math.sqrt(distance(row,center))),minimum=Math.min(...dd);const mask=dd.map(v=>v**options.p<=options.alpha**options.p*minimum**options.p+options.beta**options.p?1:0);const sum=mask.reduce((a,b)=>a+b,0);return mask.map(v=>v/sum);});
return {centers,membership:Float64Array.from(u.flat()),iterations:Math.min(iter,options.maxIterations)};}
function close(a,b,tol=5e-10){assert.equal(a.length,b.length);let error=0;for(let i=0;i<a.length;i++){error=Math.max(error,Math.abs(a[i]-b[i]));assert.ok(Math.abs(a[i]-b[i])<=tol*Math.max(1,Math.abs(b[i])),`parity mismatch ${i}: ${a[i]} vs ${b[i]}`);}return error;}
function timed(fn){const start=performance.now();const result=fn();return {ms:performance.now()-start,result};}
function median(x){return [...x].sort((a,b)=>a-b)[Math.floor(x.length/2)];}
export function runClusteringBenchmarks({n=2000,d=8,k=8,maxIterations=12,repeats=5,algorithms=['kmeans','fcm','rcm','exrcm'],firstImplementation='fast',warmups=0}={}){const random=seededRandom(2026),data=Float64Array.from({length:n*d},(_,z)=>((Math.floor(z/d)%4)*2)+random());const input={data,nSamples:n,nFeatures:d};const initCenters=Float64Array.from({length:k*d},(_,z)=>data[(Math.floor(z/d)*13%n)*d+z%d]);const initMembership=Float64Array.from({length:n*k},()=>random());for(let i=0;i<n;i++){let sum=0;for(let j=0;j<k;j++)sum+=initMembership[i*k+j];for(let j=0;j<k;j++)initMembership[i*k+j]/=sum;}
const reports=[];for(const algorithm of algorithms){const options={nClusters:k,maxIterations,tolerance:0,m:2,alpha:1.15,beta:.1,p:algorithm==='exrcm'?2:1,...(algorithm==='fcm'?{initMembership}:{initCenters})};const scratchOptions={...options,initCenters};let fastFirst,slowFirst;if(firstImplementation==='scratch'){slowFirst=timed(()=>scratch(algorithm,input,scratchOptions));fastFirst=timed(()=>run(algorithm,input,options));}else{fastFirst=timed(()=>run(algorithm,input,options));slowFirst=timed(()=>scratch(algorithm,input,scratchOptions));}let error=close(fastFirst.result.centers,slowFirst.result.centers);if(algorithm==='kmeans')assert.deepEqual(fastFirst.result.labels,slowFirst.result.labels);else error=Math.max(error,close(fastFirst.result.membership,slowFirst.result.membership));if(algorithm==='fcm'){close([fastFirst.result.objective,fastFirst.result.fpc,fastFirst.result.delta],[slowFirst.result.objective,slowFirst.result.fpc,slowFirst.result.delta]);assert.deepEqual(fastFirst.result.labels,slowFirst.result.labels);assert.equal(fastFirst.result.converged,slowFirst.result.converged);}for(let w=0;w<warmups;w++){run(algorithm,input,options);scratch(algorithm,input,scratchOptions);}const fast=[],slow=[];for(let r=0;r<repeats;r++){if(r%2){slow.push(timed(()=>scratch(algorithm,input,scratchOptions)).ms);fast.push(timed(()=>run(algorithm,input,options)).ms);}else{fast.push(timed(()=>run(algorithm,input,options)).ms);slow.push(timed(()=>scratch(algorithm,input,scratchOptions)).ms);}}
reports.push({algorithm,n,d,k,maxIterations,warmupsPlusInitialComparison:warmups+1,baseline:algorithm==='fcm'?'linear-inverse-power-normalization Float64Array, m=2 specialized':'readable scratch',membershipUpdateComplexity:algorithm==='fcm'?'O(NK) in both implementations':undefined,actualIterations:{fast:fastFirst.result.iterations,scratch:slowFirst.result.iterations},firstCallMs:{fast:fastFirst.ms,scratch:slowFirst.ms},warmMs:{fast, scratch:slow},warmMedianMs:{fast:median(fast),scratch:median(slow)},speedupOverScratch:median(slow)/median(fast),maxAbsError:error,scope:'full public fit, explicit same initialization; no Worker transport; first call not isolated process cold'});}
return reports;}

export function runClusteringFirstCall({algorithm='fcm',implementation='fast'}={}) {
 const report=runClusteringBenchmarks({algorithms:[algorithm],repeats:1,firstImplementation:implementation})[0];
 return {algorithm,implementation,mode:'first-call-in-fresh-process',elapsedMs:report.firstCallMs[implementation],n:report.n,d:report.d,k:report.k,maxIterations:report.maxIterations,actualIterations:report.actualIterations,parityMaxAbsError:report.maxAbsError,scope:'imports and fixture preparation excluded; comparison runs after timed first call'};
}
