(func (export "prototype") (param $xp i32) (param $pp i32) (param $rp i32) (param $np i32) (param $dp i32) (param $vp i32) (param $n i32) (param $d i32) (param $m i32) (param $q i32)
(local $i i32) (local $j i32) (local $f i32) (local $h i32) (local $xo i32) (local $vo i32) (local $address i32) (local $x v128) (local $value v128) (local $xs f64) (local $vs f64)
(local $p0 f64) (local $pv0 v128) (local $no0 i32) (local $ro0 i32)
(local $p1 f64) (local $pv1 v128) (local $no1 i32) (local $ro1 i32)
(local $p2 f64) (local $pv2 v128) (local $no2 i32) (local $ro2 i32)
(local $p3 f64) (local $pv3 v128) (local $no3 i32) (local $ro3 i32)
(block $id (loop $in (br_if $id (i32.ge_u (local.get $i) (local.get $n)))
(local.set $xo (i32.add (local.get $xp) (i32.mul (i32.mul (local.get $i) (local.get $d)) (i32.const 8))))
(local.set $vo (i32.add (local.get $vp) (i32.mul (i32.mul (local.get $i) (local.get $q)) (i32.const 8))))
(local.set $j (i32.const 0))
(block $jd (loop $jn (br_if $jd (i32.ge_u (i32.add (local.get $j) (i32.const 3)) (local.get $m)))
(local.set $p0 (f64.load (i32.add (local.get $pp) (i32.mul (i32.add (i32.mul (local.get $i) (local.get $m)) (i32.add (local.get $j) (i32.const 0))) (i32.const 8)))))
(local.set $pv0 (f64x2.splat (local.get $p0)))
(local.set $address (i32.add (local.get $dp) (i32.mul (i32.add (local.get $j) (i32.const 0)) (i32.const 8))))
(f64.store (local.get $address) (f64.add (f64.load (local.get $address)) (local.get $p0)))
(local.set $no0 (i32.add (local.get $np) (i32.mul (i32.mul (i32.add (local.get $j) (i32.const 0)) (local.get $d)) (i32.const 8))))
(local.set $ro0 (i32.add (local.get $rp) (i32.mul (i32.mul (i32.add (local.get $j) (i32.const 0)) (local.get $q)) (i32.const 8))))
(local.set $p1 (f64.load (i32.add (local.get $pp) (i32.mul (i32.add (i32.mul (local.get $i) (local.get $m)) (i32.add (local.get $j) (i32.const 1))) (i32.const 8)))))
(local.set $pv1 (f64x2.splat (local.get $p1)))
(local.set $address (i32.add (local.get $dp) (i32.mul (i32.add (local.get $j) (i32.const 1)) (i32.const 8))))
(f64.store (local.get $address) (f64.add (f64.load (local.get $address)) (local.get $p1)))
(local.set $no1 (i32.add (local.get $np) (i32.mul (i32.mul (i32.add (local.get $j) (i32.const 1)) (local.get $d)) (i32.const 8))))
(local.set $ro1 (i32.add (local.get $rp) (i32.mul (i32.mul (i32.add (local.get $j) (i32.const 1)) (local.get $q)) (i32.const 8))))
(local.set $p2 (f64.load (i32.add (local.get $pp) (i32.mul (i32.add (i32.mul (local.get $i) (local.get $m)) (i32.add (local.get $j) (i32.const 2))) (i32.const 8)))))
(local.set $pv2 (f64x2.splat (local.get $p2)))
(local.set $address (i32.add (local.get $dp) (i32.mul (i32.add (local.get $j) (i32.const 2)) (i32.const 8))))
(f64.store (local.get $address) (f64.add (f64.load (local.get $address)) (local.get $p2)))
(local.set $no2 (i32.add (local.get $np) (i32.mul (i32.mul (i32.add (local.get $j) (i32.const 2)) (local.get $d)) (i32.const 8))))
(local.set $ro2 (i32.add (local.get $rp) (i32.mul (i32.mul (i32.add (local.get $j) (i32.const 2)) (local.get $q)) (i32.const 8))))
(local.set $p3 (f64.load (i32.add (local.get $pp) (i32.mul (i32.add (i32.mul (local.get $i) (local.get $m)) (i32.add (local.get $j) (i32.const 3))) (i32.const 8)))))
(local.set $pv3 (f64x2.splat (local.get $p3)))
(local.set $address (i32.add (local.get $dp) (i32.mul (i32.add (local.get $j) (i32.const 3)) (i32.const 8))))
(f64.store (local.get $address) (f64.add (f64.load (local.get $address)) (local.get $p3)))
(local.set $no3 (i32.add (local.get $np) (i32.mul (i32.mul (i32.add (local.get $j) (i32.const 3)) (local.get $d)) (i32.const 8))))
(local.set $ro3 (i32.add (local.get $rp) (i32.mul (i32.mul (i32.add (local.get $j) (i32.const 3)) (local.get $q)) (i32.const 8))))
(local.set $f (i32.const 0))
(block $fd (loop $fn (br_if $fd (i32.ge_u (i32.add (local.get $f) (i32.const 1)) (local.get $d)))
(local.set $x (v128.load (i32.add (local.get $xo) (i32.mul (local.get $f) (i32.const 8)))))
(local.set $address (i32.add (local.get $no0) (i32.mul (local.get $f) (i32.const 8))))
(v128.store (local.get $address) (f64x2.add (v128.load (local.get $address)) (f64x2.mul (local.get $pv0) (local.get $x))))
(local.set $address (i32.add (local.get $no1) (i32.mul (local.get $f) (i32.const 8))))
(v128.store (local.get $address) (f64x2.add (v128.load (local.get $address)) (f64x2.mul (local.get $pv1) (local.get $x))))
(local.set $address (i32.add (local.get $no2) (i32.mul (local.get $f) (i32.const 8))))
(v128.store (local.get $address) (f64x2.add (v128.load (local.get $address)) (f64x2.mul (local.get $pv2) (local.get $x))))
(local.set $address (i32.add (local.get $no3) (i32.mul (local.get $f) (i32.const 8))))
(v128.store (local.get $address) (f64x2.add (v128.load (local.get $address)) (f64x2.mul (local.get $pv3) (local.get $x))))
(local.set $f (i32.add (local.get $f) (i32.const 2))) (br $fn)))
(if (i32.lt_u (local.get $f) (local.get $d)) (then
(local.set $xs (f64.load (i32.add (local.get $xo) (i32.mul (local.get $f) (i32.const 8)))))
(local.set $address (i32.add (local.get $no0) (i32.mul (local.get $f) (i32.const 8))))
(f64.store (local.get $address) (f64.add (f64.load (local.get $address)) (f64.mul (local.get $p0) (local.get $xs))))
(local.set $address (i32.add (local.get $no1) (i32.mul (local.get $f) (i32.const 8))))
(f64.store (local.get $address) (f64.add (f64.load (local.get $address)) (f64.mul (local.get $p1) (local.get $xs))))
(local.set $address (i32.add (local.get $no2) (i32.mul (local.get $f) (i32.const 8))))
(f64.store (local.get $address) (f64.add (f64.load (local.get $address)) (f64.mul (local.get $p2) (local.get $xs))))
(local.set $address (i32.add (local.get $no3) (i32.mul (local.get $f) (i32.const 8))))
(f64.store (local.get $address) (f64.add (f64.load (local.get $address)) (f64.mul (local.get $p3) (local.get $xs))))
))
(local.set $h (i32.const 0))
(block $hd (loop $hn (br_if $hd (i32.ge_u (i32.add (local.get $h) (i32.const 1)) (local.get $q)))
(local.set $address (i32.add (local.get $vo) (i32.mul (local.get $h) (i32.const 8))))
(local.set $value (v128.load (local.get $address)))
(local.set $value (f64x2.add (local.get $value) (f64x2.mul (local.get $pv0) (v128.load (i32.add (local.get $ro0) (i32.mul (local.get $h) (i32.const 8)))))))
(local.set $value (f64x2.add (local.get $value) (f64x2.mul (local.get $pv1) (v128.load (i32.add (local.get $ro1) (i32.mul (local.get $h) (i32.const 8)))))))
(local.set $value (f64x2.add (local.get $value) (f64x2.mul (local.get $pv2) (v128.load (i32.add (local.get $ro2) (i32.mul (local.get $h) (i32.const 8)))))))
(local.set $value (f64x2.add (local.get $value) (f64x2.mul (local.get $pv3) (v128.load (i32.add (local.get $ro3) (i32.mul (local.get $h) (i32.const 8)))))))
(v128.store (local.get $address) (local.get $value))
(local.set $h (i32.add (local.get $h) (i32.const 2))) (br $hn)))
(if (i32.lt_u (local.get $h) (local.get $q)) (then
(local.set $address (i32.add (local.get $vo) (i32.mul (local.get $h) (i32.const 8))))
(local.set $vs (f64.load (local.get $address)))
(local.set $vs (f64.add (local.get $vs) (f64.mul (local.get $p0) (f64.load (i32.add (local.get $ro0) (i32.mul (local.get $h) (i32.const 8)))))))
(local.set $vs (f64.add (local.get $vs) (f64.mul (local.get $p1) (f64.load (i32.add (local.get $ro1) (i32.mul (local.get $h) (i32.const 8)))))))
(local.set $vs (f64.add (local.get $vs) (f64.mul (local.get $p2) (f64.load (i32.add (local.get $ro2) (i32.mul (local.get $h) (i32.const 8)))))))
(local.set $vs (f64.add (local.get $vs) (f64.mul (local.get $p3) (f64.load (i32.add (local.get $ro3) (i32.mul (local.get $h) (i32.const 8)))))))
(f64.store (local.get $address) (local.get $vs))))
(local.set $j (i32.add (local.get $j) (i32.const 4))) (br $jn)))
(if (i32.lt_u (local.get $j) (local.get $m)) (then
(call $prototype_solo (local.get $xo)
(i32.add (local.get $pp) (i32.mul (i32.add (i32.mul (local.get $i) (local.get $m)) (local.get $j)) (i32.const 8)))
(i32.add (local.get $rp) (i32.mul (i32.mul (local.get $j) (local.get $q)) (i32.const 8)))
(i32.add (local.get $np) (i32.mul (i32.mul (local.get $j) (local.get $d)) (i32.const 8)))
(i32.add (local.get $dp) (i32.mul (local.get $j) (i32.const 8)))
(local.get $vo) (i32.const 1) (local.get $d) (i32.sub (local.get $m) (local.get $j)) (local.get $q))))
(local.set $i (i32.add (local.get $i) (i32.const 1))) (br $in)))
)
