(module
 (memory (export "memory") 1)
 (func (export "rotate") (param $gp i32) (param $vp i32) (param $dim i32) (param $a i32) (param $b i32) (param $c f64) (param $s f64)
  (local $j i32) (local $ap i32) (local $bp i32) (local $ja f64) (local $jb f64) (local $na f64) (local $nb f64)
  (local $cv v128) (local $sv v128) (local $av v128) (local $bv v128)
  (local.set $ap (i32.add (local.get $gp) (i32.mul (i32.mul (local.get $a) (local.get $dim)) (i32.const 8))))
  (local.set $bp (i32.add (local.get $gp) (i32.mul (i32.mul (local.get $b) (local.get $dim)) (i32.const 8))))
  (block $done (loop $next
   (br_if $done (i32.ge_u (local.get $j) (local.get $dim)))
   (if (i32.and (i32.ne (local.get $j) (local.get $a)) (i32.ne (local.get $j) (local.get $b))) (then
    (local.set $ja (f64.load (i32.add (local.get $ap) (i32.mul (local.get $j) (i32.const 8)))))
    (local.set $jb (f64.load (i32.add (local.get $bp) (i32.mul (local.get $j) (i32.const 8)))))
    (local.set $na (f64.sub (f64.mul (local.get $c) (local.get $ja)) (f64.mul (local.get $s) (local.get $jb))))
    (local.set $nb (f64.add (f64.mul (local.get $s) (local.get $ja)) (f64.mul (local.get $c) (local.get $jb))))
    (f64.store (i32.add (local.get $ap) (i32.mul (local.get $j) (i32.const 8))) (local.get $na))
    (f64.store (i32.add (local.get $gp) (i32.mul (i32.add (i32.mul (local.get $j) (local.get $dim)) (local.get $a)) (i32.const 8))) (local.get $na))
    (f64.store (i32.add (local.get $bp) (i32.mul (local.get $j) (i32.const 8))) (local.get $nb))
    (f64.store (i32.add (local.get $gp) (i32.mul (i32.add (i32.mul (local.get $j) (local.get $dim)) (local.get $b)) (i32.const 8))) (local.get $nb))
   ))
   (local.set $j (i32.add (local.get $j) (i32.const 1))) (br $next)
  ))
  (local.set $j (i32.const 0))
  (local.set $ap (i32.add (local.get $vp) (i32.mul (i32.mul (local.get $a) (local.get $dim)) (i32.const 8))))
  (local.set $bp (i32.add (local.get $vp) (i32.mul (i32.mul (local.get $b) (local.get $dim)) (i32.const 8))))
  (local.set $cv (f64x2.splat (local.get $c))) (local.set $sv (f64x2.splat (local.get $s)))
  (block $vectors_done (loop $vectors_next
   (br_if $vectors_done (i32.ge_u (i32.add (local.get $j) (i32.const 1)) (local.get $dim)))
   (local.set $av (v128.load (i32.add (local.get $ap) (i32.mul (local.get $j) (i32.const 8)))))
   (local.set $bv (v128.load (i32.add (local.get $bp) (i32.mul (local.get $j) (i32.const 8)))))
   (v128.store (i32.add (local.get $ap) (i32.mul (local.get $j) (i32.const 8))) (f64x2.sub (f64x2.mul (local.get $cv) (local.get $av)) (f64x2.mul (local.get $sv) (local.get $bv))))
   (v128.store (i32.add (local.get $bp) (i32.mul (local.get $j) (i32.const 8))) (f64x2.add (f64x2.mul (local.get $sv) (local.get $av)) (f64x2.mul (local.get $cv) (local.get $bv))))
   (local.set $j (i32.add (local.get $j) (i32.const 2))) (br $vectors_next)
  ))
  (if (i32.lt_u (local.get $j) (local.get $dim)) (then
   (local.set $ja (f64.load (i32.add (local.get $ap) (i32.mul (local.get $j) (i32.const 8)))))
   (local.set $jb (f64.load (i32.add (local.get $bp) (i32.mul (local.get $j) (i32.const 8)))))
   (f64.store (i32.add (local.get $ap) (i32.mul (local.get $j) (i32.const 8))) (f64.sub (f64.mul (local.get $c) (local.get $ja)) (f64.mul (local.get $s) (local.get $jb))))
   (f64.store (i32.add (local.get $bp) (i32.mul (local.get $j) (i32.const 8))) (f64.add (f64.mul (local.get $s) (local.get $ja)) (f64.mul (local.get $c) (local.get $jb))))
  ))
 )
)
