(func (export "prototype") (param $xp i32) (param $pp i32) (param $rp i32) (param $np i32) (param $dp i32) (param $vp i32) (param $n i32) (param $d i32) (param $m i32) (param $q i32)
 (local $i i32) (local $j i32) (local $f i32) (local $h i32) (local $xo i32) (local $no i32) (local $vo i32) (local $ro i32) (local $p f64) (local $pv v128) (local $address i32)
 (block $id (loop $in (br_if $id (i32.ge_u (local.get $i) (local.get $n)))
  (local.set $xo (i32.add (local.get $xp) (i32.mul (i32.mul (local.get $i) (local.get $d)) (i32.const 8))))
  (local.set $vo (i32.add (local.get $vp) (i32.mul (i32.mul (local.get $i) (local.get $q)) (i32.const 8))))
  (local.set $j (i32.const 0))
  (block $jd (loop $jn (br_if $jd (i32.ge_u (local.get $j) (local.get $m)))
   (local.set $p (f64.load (i32.add (local.get $pp) (i32.mul (i32.add (i32.mul (local.get $i) (local.get $m)) (local.get $j)) (i32.const 8)))))
   (local.set $pv (f64x2.splat (local.get $p)))
   (local.set $address (i32.add (local.get $dp) (i32.mul (local.get $j) (i32.const 8))))
   (f64.store (local.get $address) (f64.add (f64.load (local.get $address)) (local.get $p)))
   (local.set $no (i32.add (local.get $np) (i32.mul (i32.mul (local.get $j) (local.get $d)) (i32.const 8))))
   (local.set $ro (i32.add (local.get $rp) (i32.mul (i32.mul (local.get $j) (local.get $q)) (i32.const 8))))
   (local.set $f (i32.const 0))
   (block $fd (loop $fn (br_if $fd (i32.ge_u (i32.add (local.get $f) (i32.const 1)) (local.get $d)))
    (local.set $address (i32.add (local.get $no) (i32.mul (local.get $f) (i32.const 8))))
    (v128.store (local.get $address) (f64x2.add (v128.load (local.get $address)) (f64x2.mul (local.get $pv) (v128.load (i32.add (local.get $xo) (i32.mul (local.get $f) (i32.const 8)))))))
    (local.set $f (i32.add (local.get $f) (i32.const 2))) (br $fn)
   ))
   (if (i32.lt_u (local.get $f) (local.get $d)) (then
    (local.set $address (i32.add (local.get $no) (i32.mul (local.get $f) (i32.const 8))))
    (f64.store (local.get $address) (f64.add (f64.load (local.get $address)) (f64.mul (local.get $p) (f64.load (i32.add (local.get $xo) (i32.mul (local.get $f) (i32.const 8)))))))
   ))
   (local.set $h (i32.const 0))
   (block $hd (loop $hn (br_if $hd (i32.ge_u (i32.add (local.get $h) (i32.const 1)) (local.get $q)))
    (local.set $address (i32.add (local.get $vo) (i32.mul (local.get $h) (i32.const 8))))
    (v128.store (local.get $address) (f64x2.add (v128.load (local.get $address)) (f64x2.mul (local.get $pv) (v128.load (i32.add (local.get $ro) (i32.mul (local.get $h) (i32.const 8)))))))
    (local.set $h (i32.add (local.get $h) (i32.const 2))) (br $hn)
   ))
   (if (i32.lt_u (local.get $h) (local.get $q)) (then
    (local.set $address (i32.add (local.get $vo) (i32.mul (local.get $h) (i32.const 8))))
    (f64.store (local.get $address) (f64.add (f64.load (local.get $address)) (f64.mul (local.get $p) (f64.load (i32.add (local.get $ro) (i32.mul (local.get $h) (i32.const 8)))))))
   ))
   (local.set $j (i32.add (local.get $j) (i32.const 1))) (br $jn)
  ))
  (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $in)
 ))
)
